// Code generated by ent, DO NOT EDIT.

package upstreamevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLTE(FieldID, id))
}

// UpstreamConfigID applies equality check predicate on the "upstream_config_id" field. It's identical to UpstreamConfigIDEQ.
func UpstreamConfigID(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldUpstreamConfigID, v))
}

// UpstreamKeyID applies equality check predicate on the "upstream_key_id" field. It's identical to UpstreamKeyIDEQ.
func UpstreamKeyID(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldUpstreamKeyID, v))
}

// SyncRunID applies equality check predicate on the "sync_run_id" field. It's identical to SyncRunIDEQ.
func SyncRunID(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldSyncRunID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldAccountID, v))
}

// EventKey applies equality check predicate on the "event_key" field. It's identical to EventKeyEQ.
func EventKey(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldEventKey, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldEventType, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldSeverity, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldSource, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldMessage, v))
}

// OccurredAt applies equality check predicate on the "occurred_at" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpstreamConfigIDEQ applies the EQ predicate on the "upstream_config_id" field.
func UpstreamConfigIDEQ(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldUpstreamConfigID, v))
}

// UpstreamConfigIDNEQ applies the NEQ predicate on the "upstream_config_id" field.
func UpstreamConfigIDNEQ(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldUpstreamConfigID, v))
}

// UpstreamConfigIDIn applies the In predicate on the "upstream_config_id" field.
func UpstreamConfigIDIn(vs ...int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldUpstreamConfigID, vs...))
}

// UpstreamConfigIDNotIn applies the NotIn predicate on the "upstream_config_id" field.
func UpstreamConfigIDNotIn(vs ...int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldUpstreamConfigID, vs...))
}

// UpstreamKeyIDEQ applies the EQ predicate on the "upstream_key_id" field.
func UpstreamKeyIDEQ(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldUpstreamKeyID, v))
}

// UpstreamKeyIDNEQ applies the NEQ predicate on the "upstream_key_id" field.
func UpstreamKeyIDNEQ(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldUpstreamKeyID, v))
}

// UpstreamKeyIDIn applies the In predicate on the "upstream_key_id" field.
func UpstreamKeyIDIn(vs ...int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldUpstreamKeyID, vs...))
}

// UpstreamKeyIDNotIn applies the NotIn predicate on the "upstream_key_id" field.
func UpstreamKeyIDNotIn(vs ...int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldUpstreamKeyID, vs...))
}

// UpstreamKeyIDIsNil applies the IsNil predicate on the "upstream_key_id" field.
func UpstreamKeyIDIsNil() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIsNull(FieldUpstreamKeyID))
}

// UpstreamKeyIDNotNil applies the NotNil predicate on the "upstream_key_id" field.
func UpstreamKeyIDNotNil() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotNull(FieldUpstreamKeyID))
}

// SyncRunIDEQ applies the EQ predicate on the "sync_run_id" field.
func SyncRunIDEQ(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldSyncRunID, v))
}

// SyncRunIDNEQ applies the NEQ predicate on the "sync_run_id" field.
func SyncRunIDNEQ(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldSyncRunID, v))
}

// SyncRunIDIn applies the In predicate on the "sync_run_id" field.
func SyncRunIDIn(vs ...int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldSyncRunID, vs...))
}

// SyncRunIDNotIn applies the NotIn predicate on the "sync_run_id" field.
func SyncRunIDNotIn(vs ...int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldSyncRunID, vs...))
}

// SyncRunIDIsNil applies the IsNil predicate on the "sync_run_id" field.
func SyncRunIDIsNil() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIsNull(FieldSyncRunID))
}

// SyncRunIDNotNil applies the NotNil predicate on the "sync_run_id" field.
func SyncRunIDNotNil() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotNull(FieldSyncRunID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotNull(FieldAccountID))
}

// EventKeyEQ applies the EQ predicate on the "event_key" field.
func EventKeyEQ(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldEventKey, v))
}

// EventKeyNEQ applies the NEQ predicate on the "event_key" field.
func EventKeyNEQ(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldEventKey, v))
}

// EventKeyIn applies the In predicate on the "event_key" field.
func EventKeyIn(vs ...string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldEventKey, vs...))
}

// EventKeyNotIn applies the NotIn predicate on the "event_key" field.
func EventKeyNotIn(vs ...string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldEventKey, vs...))
}

// EventKeyGT applies the GT predicate on the "event_key" field.
func EventKeyGT(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGT(FieldEventKey, v))
}

// EventKeyGTE applies the GTE predicate on the "event_key" field.
func EventKeyGTE(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGTE(FieldEventKey, v))
}

// EventKeyLT applies the LT predicate on the "event_key" field.
func EventKeyLT(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLT(FieldEventKey, v))
}

// EventKeyLTE applies the LTE predicate on the "event_key" field.
func EventKeyLTE(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLTE(FieldEventKey, v))
}

// EventKeyContains applies the Contains predicate on the "event_key" field.
func EventKeyContains(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldContains(FieldEventKey, v))
}

// EventKeyHasPrefix applies the HasPrefix predicate on the "event_key" field.
func EventKeyHasPrefix(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldHasPrefix(FieldEventKey, v))
}

// EventKeyHasSuffix applies the HasSuffix predicate on the "event_key" field.
func EventKeyHasSuffix(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldHasSuffix(FieldEventKey, v))
}

// EventKeyIsNil applies the IsNil predicate on the "event_key" field.
func EventKeyIsNil() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIsNull(FieldEventKey))
}

// EventKeyNotNil applies the NotNil predicate on the "event_key" field.
func EventKeyNotNil() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotNull(FieldEventKey))
}

// EventKeyEqualFold applies the EqualFold predicate on the "event_key" field.
func EventKeyEqualFold(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEqualFold(FieldEventKey, v))
}

// EventKeyContainsFold applies the ContainsFold predicate on the "event_key" field.
func EventKeyContainsFold(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldContainsFold(FieldEventKey, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldContainsFold(FieldEventType, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldContainsFold(FieldSeverity, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldContainsFold(FieldSource, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldContainsFold(FieldMessage, v))
}

// OccurredAtEQ applies the EQ predicate on the "occurred_at" field.
func OccurredAtEQ(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurred_at" field.
func OccurredAtNEQ(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurred_at" field.
func OccurredAtIn(vs ...time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurred_at" field.
func OccurredAtNotIn(vs ...time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurred_at" field.
func OccurredAtGT(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurred_at" field.
func OccurredAtGTE(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurred_at" field.
func OccurredAtLT(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurred_at" field.
func OccurredAtLTE(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLTE(FieldOccurredAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// HasConfig applies the HasEdge predicate on the "config" edge.
func HasConfig() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConfigTable, ConfigColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConfigWith applies the HasEdge predicate on the "config" edge with a given conditions (other predicates).
func HasConfigWith(preds ...predicate.UpstreamConfig) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(func(s *sql.Selector) {
		step := newConfigStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasKey applies the HasEdge predicate on the "key" edge.
func HasKey() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, KeyTable, KeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeyWith applies the HasEdge predicate on the "key" edge with a given conditions (other predicates).
func HasKeyWith(preds ...predicate.UpstreamKey) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(func(s *sql.Selector) {
		step := newKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRun applies the HasEdge predicate on the "run" edge.
func HasRun() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RunTable, RunColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRunWith applies the HasEdge predicate on the "run" edge with a given conditions (other predicates).
func HasRunWith(preds ...predicate.UpstreamSyncRun) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(func(s *sql.Selector) {
		step := newRunStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIncidents applies the HasEdge predicate on the "incidents" edge.
func HasIncidents() predicate.UpstreamEvent {
	return predicate.UpstreamEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IncidentsTable, IncidentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIncidentsWith applies the HasEdge predicate on the "incidents" edge with a given conditions (other predicates).
func HasIncidentsWith(preds ...predicate.UpstreamIncident) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(func(s *sql.Selector) {
		step := newIncidentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamEvent) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamEvent) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamEvent) predicate.UpstreamEvent {
	return predicate.UpstreamEvent(sql.NotPredicates(p))
}
