// Code generated by ent, DO NOT EDIT.

package proxybinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the proxybinding type in the database.
	Label = "proxy_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBindingType holds the string denoting the binding_type field in the database.
	FieldBindingType = "binding_type"
	// FieldProxyID holds the string denoting the proxy_id field in the database.
	FieldProxyID = "proxy_id"
	// FieldProxyIPGroupID holds the string denoting the proxy_ip_group_id field in the database.
	FieldProxyIPGroupID = "proxy_ip_group_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the proxybinding in the database.
	Table = "proxy_bindings"
)

// Columns holds all SQL columns for proxybinding fields.
var Columns = []string{
	FieldID,
	FieldBindingType,
	FieldProxyID,
	FieldProxyIPGroupID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// BindingTypeValidator is a validator for the "binding_type" field. It is called by the builders before save.
	BindingTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProxyBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBindingType orders the results by the binding_type field.
func ByBindingType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindingType, opts...).ToFunc()
}

// ByProxyID orders the results by the proxy_id field.
func ByProxyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyID, opts...).ToFunc()
}

// ByProxyIPGroupID orders the results by the proxy_ip_group_id field.
func ByProxyIPGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyIPGroupID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
