// Code generated by ent, DO NOT EDIT.

package groupratesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldGroupID, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldRateMultiplier, v))
}

// PeakRateEnabled applies equality check predicate on the "peak_rate_enabled" field. It's identical to PeakRateEnabledEQ.
func PeakRateEnabled(v bool) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldPeakRateEnabled, v))
}

// PeakStart applies equality check predicate on the "peak_start" field. It's identical to PeakStartEQ.
func PeakStart(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldPeakStart, v))
}

// PeakEnd applies equality check predicate on the "peak_end" field. It's identical to PeakEndEQ.
func PeakEnd(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldPeakEnd, v))
}

// PeakRateMultiplier applies equality check predicate on the "peak_rate_multiplier" field. It's identical to PeakRateMultiplierEQ.
func PeakRateMultiplier(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldPeakRateMultiplier, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldTimezone, v))
}

// EffectiveAt applies equality check predicate on the "effective_at" field. It's identical to EffectiveAtEQ.
func EffectiveAt(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldEffectiveAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNotIn(FieldGroupID, vs...))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLTE(FieldRateMultiplier, v))
}

// PeakRateEnabledEQ applies the EQ predicate on the "peak_rate_enabled" field.
func PeakRateEnabledEQ(v bool) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldPeakRateEnabled, v))
}

// PeakRateEnabledNEQ applies the NEQ predicate on the "peak_rate_enabled" field.
func PeakRateEnabledNEQ(v bool) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNEQ(FieldPeakRateEnabled, v))
}

// PeakStartEQ applies the EQ predicate on the "peak_start" field.
func PeakStartEQ(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldPeakStart, v))
}

// PeakStartNEQ applies the NEQ predicate on the "peak_start" field.
func PeakStartNEQ(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNEQ(FieldPeakStart, v))
}

// PeakStartIn applies the In predicate on the "peak_start" field.
func PeakStartIn(vs ...string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldIn(FieldPeakStart, vs...))
}

// PeakStartNotIn applies the NotIn predicate on the "peak_start" field.
func PeakStartNotIn(vs ...string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNotIn(FieldPeakStart, vs...))
}

// PeakStartGT applies the GT predicate on the "peak_start" field.
func PeakStartGT(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGT(FieldPeakStart, v))
}

// PeakStartGTE applies the GTE predicate on the "peak_start" field.
func PeakStartGTE(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGTE(FieldPeakStart, v))
}

// PeakStartLT applies the LT predicate on the "peak_start" field.
func PeakStartLT(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLT(FieldPeakStart, v))
}

// PeakStartLTE applies the LTE predicate on the "peak_start" field.
func PeakStartLTE(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLTE(FieldPeakStart, v))
}

// PeakStartContains applies the Contains predicate on the "peak_start" field.
func PeakStartContains(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldContains(FieldPeakStart, v))
}

// PeakStartHasPrefix applies the HasPrefix predicate on the "peak_start" field.
func PeakStartHasPrefix(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldHasPrefix(FieldPeakStart, v))
}

// PeakStartHasSuffix applies the HasSuffix predicate on the "peak_start" field.
func PeakStartHasSuffix(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldHasSuffix(FieldPeakStart, v))
}

// PeakStartEqualFold applies the EqualFold predicate on the "peak_start" field.
func PeakStartEqualFold(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEqualFold(FieldPeakStart, v))
}

// PeakStartContainsFold applies the ContainsFold predicate on the "peak_start" field.
func PeakStartContainsFold(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldContainsFold(FieldPeakStart, v))
}

// PeakEndEQ applies the EQ predicate on the "peak_end" field.
func PeakEndEQ(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldPeakEnd, v))
}

// PeakEndNEQ applies the NEQ predicate on the "peak_end" field.
func PeakEndNEQ(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNEQ(FieldPeakEnd, v))
}

// PeakEndIn applies the In predicate on the "peak_end" field.
func PeakEndIn(vs ...string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldIn(FieldPeakEnd, vs...))
}

// PeakEndNotIn applies the NotIn predicate on the "peak_end" field.
func PeakEndNotIn(vs ...string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNotIn(FieldPeakEnd, vs...))
}

// PeakEndGT applies the GT predicate on the "peak_end" field.
func PeakEndGT(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGT(FieldPeakEnd, v))
}

// PeakEndGTE applies the GTE predicate on the "peak_end" field.
func PeakEndGTE(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGTE(FieldPeakEnd, v))
}

// PeakEndLT applies the LT predicate on the "peak_end" field.
func PeakEndLT(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLT(FieldPeakEnd, v))
}

// PeakEndLTE applies the LTE predicate on the "peak_end" field.
func PeakEndLTE(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLTE(FieldPeakEnd, v))
}

// PeakEndContains applies the Contains predicate on the "peak_end" field.
func PeakEndContains(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldContains(FieldPeakEnd, v))
}

// PeakEndHasPrefix applies the HasPrefix predicate on the "peak_end" field.
func PeakEndHasPrefix(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldHasPrefix(FieldPeakEnd, v))
}

// PeakEndHasSuffix applies the HasSuffix predicate on the "peak_end" field.
func PeakEndHasSuffix(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldHasSuffix(FieldPeakEnd, v))
}

// PeakEndEqualFold applies the EqualFold predicate on the "peak_end" field.
func PeakEndEqualFold(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEqualFold(FieldPeakEnd, v))
}

// PeakEndContainsFold applies the ContainsFold predicate on the "peak_end" field.
func PeakEndContainsFold(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldContainsFold(FieldPeakEnd, v))
}

// PeakRateMultiplierEQ applies the EQ predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierEQ(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierNEQ applies the NEQ predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierNEQ(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNEQ(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierIn applies the In predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierIn(vs ...float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldIn(FieldPeakRateMultiplier, vs...))
}

// PeakRateMultiplierNotIn applies the NotIn predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierNotIn(vs ...float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNotIn(FieldPeakRateMultiplier, vs...))
}

// PeakRateMultiplierGT applies the GT predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierGT(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGT(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierGTE applies the GTE predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierGTE(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGTE(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierLT applies the LT predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierLT(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLT(FieldPeakRateMultiplier, v))
}

// PeakRateMultiplierLTE applies the LTE predicate on the "peak_rate_multiplier" field.
func PeakRateMultiplierLTE(v float64) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLTE(FieldPeakRateMultiplier, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldContainsFold(FieldTimezone, v))
}

// EffectiveAtEQ applies the EQ predicate on the "effective_at" field.
func EffectiveAtEQ(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldEffectiveAt, v))
}

// EffectiveAtNEQ applies the NEQ predicate on the "effective_at" field.
func EffectiveAtNEQ(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNEQ(FieldEffectiveAt, v))
}

// EffectiveAtIn applies the In predicate on the "effective_at" field.
func EffectiveAtIn(vs ...time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldIn(FieldEffectiveAt, vs...))
}

// EffectiveAtNotIn applies the NotIn predicate on the "effective_at" field.
func EffectiveAtNotIn(vs ...time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNotIn(FieldEffectiveAt, vs...))
}

// EffectiveAtGT applies the GT predicate on the "effective_at" field.
func EffectiveAtGT(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGT(FieldEffectiveAt, v))
}

// EffectiveAtGTE applies the GTE predicate on the "effective_at" field.
func EffectiveAtGTE(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGTE(FieldEffectiveAt, v))
}

// EffectiveAtLT applies the LT predicate on the "effective_at" field.
func EffectiveAtLT(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLT(FieldEffectiveAt, v))
}

// EffectiveAtLTE applies the LTE predicate on the "effective_at" field.
func EffectiveAtLTE(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLTE(FieldEffectiveAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.FieldLTE(FieldCreatedAt, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupRateSnapshot) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupRateSnapshot) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupRateSnapshot) predicate.GroupRateSnapshot {
	return predicate.GroupRateSnapshot(sql.NotPredicates(p))
}
