// Code generated by ent, DO NOT EDIT.

package upstreamincident

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpstreamConfigID applies equality check predicate on the "upstream_config_id" field. It's identical to UpstreamConfigIDEQ.
func UpstreamConfigID(v int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldUpstreamConfigID, v))
}

// UpstreamKeyID applies equality check predicate on the "upstream_key_id" field. It's identical to UpstreamKeyIDEQ.
func UpstreamKeyID(v int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldUpstreamKeyID, v))
}

// SourceEventID applies equality check predicate on the "source_event_id" field. It's identical to SourceEventIDEQ.
func SourceEventID(v int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldSourceEventID, v))
}

// IncidentKey applies equality check predicate on the "incident_key" field. It's identical to IncidentKeyEQ.
func IncidentKey(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldIncidentKey, v))
}

// IncidentType applies equality check predicate on the "incident_type" field. It's identical to IncidentTypeEQ.
func IncidentType(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldIncidentType, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldSeverity, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldStatus, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldDescription, v))
}

// MetricValue applies equality check predicate on the "metric_value" field. It's identical to MetricValueEQ.
func MetricValue(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldMetricValue, v))
}

// ThresholdValue applies equality check predicate on the "threshold_value" field. It's identical to ThresholdValueEQ.
func ThresholdValue(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldThresholdValue, v))
}

// OccurrenceCount applies equality check predicate on the "occurrence_count" field. It's identical to OccurrenceCountEQ.
func OccurrenceCount(v int) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldOccurrenceCount, v))
}

// FirstSeenAt applies equality check predicate on the "first_seen_at" field. It's identical to FirstSeenAtEQ.
func FirstSeenAt(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldFirstSeenAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldLastSeenAt, v))
}

// AcknowledgedAt applies equality check predicate on the "acknowledged_at" field. It's identical to AcknowledgedAtEQ.
func AcknowledgedAt(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldAcknowledgedAt, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldResolvedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpstreamConfigIDEQ applies the EQ predicate on the "upstream_config_id" field.
func UpstreamConfigIDEQ(v int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldUpstreamConfigID, v))
}

// UpstreamConfigIDNEQ applies the NEQ predicate on the "upstream_config_id" field.
func UpstreamConfigIDNEQ(v int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldUpstreamConfigID, v))
}

// UpstreamConfigIDIn applies the In predicate on the "upstream_config_id" field.
func UpstreamConfigIDIn(vs ...int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldUpstreamConfigID, vs...))
}

// UpstreamConfigIDNotIn applies the NotIn predicate on the "upstream_config_id" field.
func UpstreamConfigIDNotIn(vs ...int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldUpstreamConfigID, vs...))
}

// UpstreamKeyIDEQ applies the EQ predicate on the "upstream_key_id" field.
func UpstreamKeyIDEQ(v int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldUpstreamKeyID, v))
}

// UpstreamKeyIDNEQ applies the NEQ predicate on the "upstream_key_id" field.
func UpstreamKeyIDNEQ(v int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldUpstreamKeyID, v))
}

// UpstreamKeyIDIn applies the In predicate on the "upstream_key_id" field.
func UpstreamKeyIDIn(vs ...int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldUpstreamKeyID, vs...))
}

// UpstreamKeyIDNotIn applies the NotIn predicate on the "upstream_key_id" field.
func UpstreamKeyIDNotIn(vs ...int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldUpstreamKeyID, vs...))
}

// UpstreamKeyIDIsNil applies the IsNil predicate on the "upstream_key_id" field.
func UpstreamKeyIDIsNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIsNull(FieldUpstreamKeyID))
}

// UpstreamKeyIDNotNil applies the NotNil predicate on the "upstream_key_id" field.
func UpstreamKeyIDNotNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotNull(FieldUpstreamKeyID))
}

// SourceEventIDEQ applies the EQ predicate on the "source_event_id" field.
func SourceEventIDEQ(v int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldSourceEventID, v))
}

// SourceEventIDNEQ applies the NEQ predicate on the "source_event_id" field.
func SourceEventIDNEQ(v int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldSourceEventID, v))
}

// SourceEventIDIn applies the In predicate on the "source_event_id" field.
func SourceEventIDIn(vs ...int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldSourceEventID, vs...))
}

// SourceEventIDNotIn applies the NotIn predicate on the "source_event_id" field.
func SourceEventIDNotIn(vs ...int64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldSourceEventID, vs...))
}

// SourceEventIDIsNil applies the IsNil predicate on the "source_event_id" field.
func SourceEventIDIsNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIsNull(FieldSourceEventID))
}

// SourceEventIDNotNil applies the NotNil predicate on the "source_event_id" field.
func SourceEventIDNotNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotNull(FieldSourceEventID))
}

// IncidentKeyEQ applies the EQ predicate on the "incident_key" field.
func IncidentKeyEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldIncidentKey, v))
}

// IncidentKeyNEQ applies the NEQ predicate on the "incident_key" field.
func IncidentKeyNEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldIncidentKey, v))
}

// IncidentKeyIn applies the In predicate on the "incident_key" field.
func IncidentKeyIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldIncidentKey, vs...))
}

// IncidentKeyNotIn applies the NotIn predicate on the "incident_key" field.
func IncidentKeyNotIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldIncidentKey, vs...))
}

// IncidentKeyGT applies the GT predicate on the "incident_key" field.
func IncidentKeyGT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldIncidentKey, v))
}

// IncidentKeyGTE applies the GTE predicate on the "incident_key" field.
func IncidentKeyGTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldIncidentKey, v))
}

// IncidentKeyLT applies the LT predicate on the "incident_key" field.
func IncidentKeyLT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldIncidentKey, v))
}

// IncidentKeyLTE applies the LTE predicate on the "incident_key" field.
func IncidentKeyLTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldIncidentKey, v))
}

// IncidentKeyContains applies the Contains predicate on the "incident_key" field.
func IncidentKeyContains(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContains(FieldIncidentKey, v))
}

// IncidentKeyHasPrefix applies the HasPrefix predicate on the "incident_key" field.
func IncidentKeyHasPrefix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasPrefix(FieldIncidentKey, v))
}

// IncidentKeyHasSuffix applies the HasSuffix predicate on the "incident_key" field.
func IncidentKeyHasSuffix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasSuffix(FieldIncidentKey, v))
}

// IncidentKeyEqualFold applies the EqualFold predicate on the "incident_key" field.
func IncidentKeyEqualFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEqualFold(FieldIncidentKey, v))
}

// IncidentKeyContainsFold applies the ContainsFold predicate on the "incident_key" field.
func IncidentKeyContainsFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContainsFold(FieldIncidentKey, v))
}

// IncidentTypeEQ applies the EQ predicate on the "incident_type" field.
func IncidentTypeEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldIncidentType, v))
}

// IncidentTypeNEQ applies the NEQ predicate on the "incident_type" field.
func IncidentTypeNEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldIncidentType, v))
}

// IncidentTypeIn applies the In predicate on the "incident_type" field.
func IncidentTypeIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldIncidentType, vs...))
}

// IncidentTypeNotIn applies the NotIn predicate on the "incident_type" field.
func IncidentTypeNotIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldIncidentType, vs...))
}

// IncidentTypeGT applies the GT predicate on the "incident_type" field.
func IncidentTypeGT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldIncidentType, v))
}

// IncidentTypeGTE applies the GTE predicate on the "incident_type" field.
func IncidentTypeGTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldIncidentType, v))
}

// IncidentTypeLT applies the LT predicate on the "incident_type" field.
func IncidentTypeLT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldIncidentType, v))
}

// IncidentTypeLTE applies the LTE predicate on the "incident_type" field.
func IncidentTypeLTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldIncidentType, v))
}

// IncidentTypeContains applies the Contains predicate on the "incident_type" field.
func IncidentTypeContains(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContains(FieldIncidentType, v))
}

// IncidentTypeHasPrefix applies the HasPrefix predicate on the "incident_type" field.
func IncidentTypeHasPrefix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasPrefix(FieldIncidentType, v))
}

// IncidentTypeHasSuffix applies the HasSuffix predicate on the "incident_type" field.
func IncidentTypeHasSuffix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasSuffix(FieldIncidentType, v))
}

// IncidentTypeEqualFold applies the EqualFold predicate on the "incident_type" field.
func IncidentTypeEqualFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEqualFold(FieldIncidentType, v))
}

// IncidentTypeContainsFold applies the ContainsFold predicate on the "incident_type" field.
func IncidentTypeContainsFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContainsFold(FieldIncidentType, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContainsFold(FieldSeverity, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContainsFold(FieldStatus, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldContainsFold(FieldDescription, v))
}

// MetricValueEQ applies the EQ predicate on the "metric_value" field.
func MetricValueEQ(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldMetricValue, v))
}

// MetricValueNEQ applies the NEQ predicate on the "metric_value" field.
func MetricValueNEQ(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldMetricValue, v))
}

// MetricValueIn applies the In predicate on the "metric_value" field.
func MetricValueIn(vs ...float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldMetricValue, vs...))
}

// MetricValueNotIn applies the NotIn predicate on the "metric_value" field.
func MetricValueNotIn(vs ...float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldMetricValue, vs...))
}

// MetricValueGT applies the GT predicate on the "metric_value" field.
func MetricValueGT(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldMetricValue, v))
}

// MetricValueGTE applies the GTE predicate on the "metric_value" field.
func MetricValueGTE(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldMetricValue, v))
}

// MetricValueLT applies the LT predicate on the "metric_value" field.
func MetricValueLT(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldMetricValue, v))
}

// MetricValueLTE applies the LTE predicate on the "metric_value" field.
func MetricValueLTE(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldMetricValue, v))
}

// MetricValueIsNil applies the IsNil predicate on the "metric_value" field.
func MetricValueIsNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIsNull(FieldMetricValue))
}

// MetricValueNotNil applies the NotNil predicate on the "metric_value" field.
func MetricValueNotNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotNull(FieldMetricValue))
}

// ThresholdValueEQ applies the EQ predicate on the "threshold_value" field.
func ThresholdValueEQ(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldThresholdValue, v))
}

// ThresholdValueNEQ applies the NEQ predicate on the "threshold_value" field.
func ThresholdValueNEQ(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldThresholdValue, v))
}

// ThresholdValueIn applies the In predicate on the "threshold_value" field.
func ThresholdValueIn(vs ...float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldThresholdValue, vs...))
}

// ThresholdValueNotIn applies the NotIn predicate on the "threshold_value" field.
func ThresholdValueNotIn(vs ...float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldThresholdValue, vs...))
}

// ThresholdValueGT applies the GT predicate on the "threshold_value" field.
func ThresholdValueGT(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldThresholdValue, v))
}

// ThresholdValueGTE applies the GTE predicate on the "threshold_value" field.
func ThresholdValueGTE(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldThresholdValue, v))
}

// ThresholdValueLT applies the LT predicate on the "threshold_value" field.
func ThresholdValueLT(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldThresholdValue, v))
}

// ThresholdValueLTE applies the LTE predicate on the "threshold_value" field.
func ThresholdValueLTE(v float64) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldThresholdValue, v))
}

// ThresholdValueIsNil applies the IsNil predicate on the "threshold_value" field.
func ThresholdValueIsNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIsNull(FieldThresholdValue))
}

// ThresholdValueNotNil applies the NotNil predicate on the "threshold_value" field.
func ThresholdValueNotNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotNull(FieldThresholdValue))
}

// OccurrenceCountEQ applies the EQ predicate on the "occurrence_count" field.
func OccurrenceCountEQ(v int) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldOccurrenceCount, v))
}

// OccurrenceCountNEQ applies the NEQ predicate on the "occurrence_count" field.
func OccurrenceCountNEQ(v int) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldOccurrenceCount, v))
}

// OccurrenceCountIn applies the In predicate on the "occurrence_count" field.
func OccurrenceCountIn(vs ...int) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldOccurrenceCount, vs...))
}

// OccurrenceCountNotIn applies the NotIn predicate on the "occurrence_count" field.
func OccurrenceCountNotIn(vs ...int) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldOccurrenceCount, vs...))
}

// OccurrenceCountGT applies the GT predicate on the "occurrence_count" field.
func OccurrenceCountGT(v int) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldOccurrenceCount, v))
}

// OccurrenceCountGTE applies the GTE predicate on the "occurrence_count" field.
func OccurrenceCountGTE(v int) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldOccurrenceCount, v))
}

// OccurrenceCountLT applies the LT predicate on the "occurrence_count" field.
func OccurrenceCountLT(v int) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldOccurrenceCount, v))
}

// OccurrenceCountLTE applies the LTE predicate on the "occurrence_count" field.
func OccurrenceCountLTE(v int) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldOccurrenceCount, v))
}

// FirstSeenAtEQ applies the EQ predicate on the "first_seen_at" field.
func FirstSeenAtEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtNEQ applies the NEQ predicate on the "first_seen_at" field.
func FirstSeenAtNEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtIn applies the In predicate on the "first_seen_at" field.
func FirstSeenAtIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtNotIn applies the NotIn predicate on the "first_seen_at" field.
func FirstSeenAtNotIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtGT applies the GT predicate on the "first_seen_at" field.
func FirstSeenAtGT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldFirstSeenAt, v))
}

// FirstSeenAtGTE applies the GTE predicate on the "first_seen_at" field.
func FirstSeenAtGTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldFirstSeenAt, v))
}

// FirstSeenAtLT applies the LT predicate on the "first_seen_at" field.
func FirstSeenAtLT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldFirstSeenAt, v))
}

// FirstSeenAtLTE applies the LTE predicate on the "first_seen_at" field.
func FirstSeenAtLTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldFirstSeenAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldLastSeenAt, v))
}

// AcknowledgedAtEQ applies the EQ predicate on the "acknowledged_at" field.
func AcknowledgedAtEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldAcknowledgedAt, v))
}

// AcknowledgedAtNEQ applies the NEQ predicate on the "acknowledged_at" field.
func AcknowledgedAtNEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldAcknowledgedAt, v))
}

// AcknowledgedAtIn applies the In predicate on the "acknowledged_at" field.
func AcknowledgedAtIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldAcknowledgedAt, vs...))
}

// AcknowledgedAtNotIn applies the NotIn predicate on the "acknowledged_at" field.
func AcknowledgedAtNotIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldAcknowledgedAt, vs...))
}

// AcknowledgedAtGT applies the GT predicate on the "acknowledged_at" field.
func AcknowledgedAtGT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldAcknowledgedAt, v))
}

// AcknowledgedAtGTE applies the GTE predicate on the "acknowledged_at" field.
func AcknowledgedAtGTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldAcknowledgedAt, v))
}

// AcknowledgedAtLT applies the LT predicate on the "acknowledged_at" field.
func AcknowledgedAtLT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldAcknowledgedAt, v))
}

// AcknowledgedAtLTE applies the LTE predicate on the "acknowledged_at" field.
func AcknowledgedAtLTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldAcknowledgedAt, v))
}

// AcknowledgedAtIsNil applies the IsNil predicate on the "acknowledged_at" field.
func AcknowledgedAtIsNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIsNull(FieldAcknowledgedAt))
}

// AcknowledgedAtNotNil applies the NotNil predicate on the "acknowledged_at" field.
func AcknowledgedAtNotNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotNull(FieldAcknowledgedAt))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.FieldNotNull(FieldResolvedAt))
}

// HasConfig applies the HasEdge predicate on the "config" edge.
func HasConfig() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConfigTable, ConfigColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConfigWith applies the HasEdge predicate on the "config" edge with a given conditions (other predicates).
func HasConfigWith(preds ...predicate.UpstreamConfig) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(func(s *sql.Selector) {
		step := newConfigStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSourceEvent applies the HasEdge predicate on the "source_event" edge.
func HasSourceEvent() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceEventTable, SourceEventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceEventWith applies the HasEdge predicate on the "source_event" edge with a given conditions (other predicates).
func HasSourceEventWith(preds ...predicate.UpstreamEvent) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(func(s *sql.Selector) {
		step := newSourceEventStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasKey applies the HasEdge predicate on the "key" edge.
func HasKey() predicate.UpstreamIncident {
	return predicate.UpstreamIncident(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, KeyTable, KeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeyWith applies the HasEdge predicate on the "key" edge with a given conditions (other predicates).
func HasKeyWith(preds ...predicate.UpstreamKey) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(func(s *sql.Selector) {
		step := newKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamIncident) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamIncident) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamIncident) predicate.UpstreamIncident {
	return predicate.UpstreamIncident(sql.NotPredicates(p))
}
