// Code generated by ent, DO NOT EDIT.

package upstreamkeyratesnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the upstreamkeyratesnapshot type in the database.
	Label = "upstream_key_rate_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUpstreamConfigID holds the string denoting the upstream_config_id field in the database.
	FieldUpstreamConfigID = "upstream_config_id"
	// FieldUpstreamKeyID holds the string denoting the upstream_key_id field in the database.
	FieldUpstreamKeyID = "upstream_key_id"
	// FieldRemoteKeyID holds the string denoting the remote_key_id field in the database.
	FieldRemoteKeyID = "remote_key_id"
	// FieldKeyNameSnapshot holds the string denoting the key_name_snapshot field in the database.
	FieldKeyNameSnapshot = "key_name_snapshot"
	// FieldKeyHashSnapshot holds the string denoting the key_hash_snapshot field in the database.
	FieldKeyHashSnapshot = "key_hash_snapshot"
	// FieldSyncRunID holds the string denoting the sync_run_id field in the database.
	FieldSyncRunID = "sync_run_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldRawRateMultiplier holds the string denoting the raw_rate_multiplier field in the database.
	FieldRawRateMultiplier = "raw_rate_multiplier"
	// FieldRechargeRate holds the string denoting the recharge_rate field in the database.
	FieldRechargeRate = "recharge_rate"
	// FieldEffectiveCostMultiplier holds the string denoting the effective_cost_multiplier field in the database.
	FieldEffectiveCostMultiplier = "effective_cost_multiplier"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldObservedAt holds the string denoting the observed_at field in the database.
	FieldObservedAt = "observed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeConfig holds the string denoting the config edge name in mutations.
	EdgeConfig = "config"
	// EdgeKey holds the string denoting the key edge name in mutations.
	EdgeKey = "key"
	// EdgeRun holds the string denoting the run edge name in mutations.
	EdgeRun = "run"
	// Table holds the table name of the upstreamkeyratesnapshot in the database.
	Table = "upstream_key_rate_snapshots"
	// ConfigTable is the table that holds the config relation/edge.
	ConfigTable = "upstream_key_rate_snapshots"
	// ConfigInverseTable is the table name for the UpstreamConfig entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamconfig" package.
	ConfigInverseTable = "upstream_configs"
	// ConfigColumn is the table column denoting the config relation/edge.
	ConfigColumn = "upstream_config_id"
	// KeyTable is the table that holds the key relation/edge.
	KeyTable = "upstream_key_rate_snapshots"
	// KeyInverseTable is the table name for the UpstreamKey entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamkey" package.
	KeyInverseTable = "upstream_keys"
	// KeyColumn is the table column denoting the key relation/edge.
	KeyColumn = "upstream_key_id"
	// RunTable is the table that holds the run relation/edge.
	RunTable = "upstream_key_rate_snapshots"
	// RunInverseTable is the table name for the UpstreamSyncRun entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamsyncrun" package.
	RunInverseTable = "upstream_sync_runs"
	// RunColumn is the table column denoting the run relation/edge.
	RunColumn = "sync_run_id"
)

// Columns holds all SQL columns for upstreamkeyratesnapshot fields.
var Columns = []string{
	FieldID,
	FieldUpstreamConfigID,
	FieldUpstreamKeyID,
	FieldRemoteKeyID,
	FieldKeyNameSnapshot,
	FieldKeyHashSnapshot,
	FieldSyncRunID,
	FieldProvider,
	FieldRawRateMultiplier,
	FieldRechargeRate,
	FieldEffectiveCostMultiplier,
	FieldSource,
	FieldObservedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultKeyNameSnapshot holds the default value on creation for the "key_name_snapshot" field.
	DefaultKeyNameSnapshot string
	// KeyNameSnapshotValidator is a validator for the "key_name_snapshot" field. It is called by the builders before save.
	KeyNameSnapshotValidator func(string) error
	// DefaultKeyHashSnapshot holds the default value on creation for the "key_hash_snapshot" field.
	DefaultKeyHashSnapshot string
	// KeyHashSnapshotValidator is a validator for the "key_hash_snapshot" field. It is called by the builders before save.
	KeyHashSnapshotValidator func(string) error
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// SourceValidator is a validator for the "source" field. It is called by the builders before save.
	SourceValidator func(string) error
	// DefaultObservedAt holds the default value on creation for the "observed_at" field.
	DefaultObservedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UpstreamKeyRateSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUpstreamConfigID orders the results by the upstream_config_id field.
func ByUpstreamConfigID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamConfigID, opts...).ToFunc()
}

// ByUpstreamKeyID orders the results by the upstream_key_id field.
func ByUpstreamKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamKeyID, opts...).ToFunc()
}

// ByRemoteKeyID orders the results by the remote_key_id field.
func ByRemoteKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemoteKeyID, opts...).ToFunc()
}

// ByKeyNameSnapshot orders the results by the key_name_snapshot field.
func ByKeyNameSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyNameSnapshot, opts...).ToFunc()
}

// ByKeyHashSnapshot orders the results by the key_hash_snapshot field.
func ByKeyHashSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyHashSnapshot, opts...).ToFunc()
}

// BySyncRunID orders the results by the sync_run_id field.
func BySyncRunID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncRunID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByRawRateMultiplier orders the results by the raw_rate_multiplier field.
func ByRawRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawRateMultiplier, opts...).ToFunc()
}

// ByRechargeRate orders the results by the recharge_rate field.
func ByRechargeRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeRate, opts...).ToFunc()
}

// ByEffectiveCostMultiplier orders the results by the effective_cost_multiplier field.
func ByEffectiveCostMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveCostMultiplier, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByObservedAt orders the results by the observed_at field.
func ByObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByConfigField orders the results by config field.
func ByConfigField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConfigStep(), sql.OrderByField(field, opts...))
	}
}

// ByKeyField orders the results by key field.
func ByKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newKeyStep(), sql.OrderByField(field, opts...))
	}
}

// ByRunField orders the results by run field.
func ByRunField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRunStep(), sql.OrderByField(field, opts...))
	}
}
func newConfigStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConfigInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConfigTable, ConfigColumn),
	)
}
func newKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(KeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, KeyTable, KeyColumn),
	)
}
func newRunStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RunInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RunTable, RunColumn),
	)
}
