-- 238_upstream_account_lifecycle.sql
-- Track ownership of upstream-derived accounts so complete sync snapshots can
-- archive only accounts that are proven to be managed by the synchronizer.

ALTER TABLE accounts
    ADD COLUMN IF NOT EXISTS upstream_lifecycle_owner VARCHAR(20) NOT NULL DEFAULT 'manual';

ALTER TABLE accounts
    ADD COLUMN IF NOT EXISTS upstream_archive_reason VARCHAR(32);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'accounts_upstream_lifecycle_owner_check'
          AND conrelid = 'accounts'::regclass
    ) THEN
        ALTER TABLE accounts
            ADD CONSTRAINT accounts_upstream_lifecycle_owner_check
            CHECK (upstream_lifecycle_owner IN ('manual', 'sync_managed'));
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'accounts_upstream_archive_reason_check'
          AND conrelid = 'accounts'::regclass
    ) THEN
        ALTER TABLE accounts
            ADD CONSTRAINT accounts_upstream_archive_reason_check
            CHECK (upstream_archive_reason IS NULL OR upstream_archive_reason = 'key_missing');
    END IF;
END $$;

-- Historical rows intentionally remain manual here. The synchronizer adopts
-- only rows whose complete runtime signature proves they were generated by
-- the upstream lifecycle. Keeping that decision out of the migration avoids
-- turning an irreversible schema rollout into a data-ownership guess.

CREATE INDEX IF NOT EXISTS idx_accounts_upstream_key_lifecycle_archive
    ON accounts(upstream_key_id, deleted_at DESC, id DESC)
    WHERE deleted_at IS NOT NULL
      AND upstream_lifecycle_owner = 'sync_managed'
      AND upstream_archive_reason = 'key_missing';

COMMENT ON COLUMN accounts.upstream_lifecycle_owner IS
    'Lifecycle owner for upstream-bound accounts: manual or sync_managed.';
COMMENT ON COLUMN accounts.upstream_archive_reason IS
    'Reason a sync-managed upstream account was soft-archived.';
