// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountproxybinding"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// AccountProxyBinding is the model entity for the AccountProxyBinding schema.
type AccountProxyBinding struct {
	config `json:"-"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// ProxyID holds the value of the "proxy_id" field.
	ProxyID int64 `json:"proxy_id,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountProxyBindingQuery when eager-loading is set.
	Edges        AccountProxyBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountProxyBindingEdges holds the relations/edges for other nodes in the graph.
type AccountProxyBindingEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Proxy holds the value of the proxy edge.
	Proxy *Proxy `json:"proxy,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountProxyBindingEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// ProxyOrErr returns the Proxy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountProxyBindingEdges) ProxyOrErr() (*Proxy, error) {
	if e.Proxy != nil {
		return e.Proxy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: proxy.Label}
	}
	return nil, &NotLoadedError{edge: "proxy"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountProxyBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountproxybinding.FieldAccountID, accountproxybinding.FieldProxyID, accountproxybinding.FieldPosition:
			values[i] = new(sql.NullInt64)
		case accountproxybinding.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountProxyBinding fields.
func (_m *AccountProxyBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountproxybinding.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountproxybinding.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = value.Int64
			}
		case accountproxybinding.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case accountproxybinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountProxyBinding.
// This includes values selected through modifiers, order, etc.
func (_m *AccountProxyBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountProxyBinding entity.
func (_m *AccountProxyBinding) QueryAccount() *AccountQuery {
	return NewAccountProxyBindingClient(_m.config).QueryAccount(_m)
}

// QueryProxy queries the "proxy" edge of the AccountProxyBinding entity.
func (_m *AccountProxyBinding) QueryProxy() *ProxyQuery {
	return NewAccountProxyBindingClient(_m.config).QueryProxy(_m)
}

// Update returns a builder for updating this AccountProxyBinding.
// Note that you need to call AccountProxyBinding.Unwrap() before calling this method if this AccountProxyBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountProxyBinding) Update() *AccountProxyBindingUpdateOne {
	return NewAccountProxyBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountProxyBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountProxyBinding) Unwrap() *AccountProxyBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountProxyBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountProxyBinding) String() string {
	var builder strings.Builder
	builder.WriteString("AccountProxyBinding(")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("proxy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProxyID))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountProxyBindings is a parsable slice of AccountProxyBinding.
type AccountProxyBindings []*AccountProxyBinding
