// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountproxybinding"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// AccountProxyBindingUpdate is the builder for updating AccountProxyBinding entities.
type AccountProxyBindingUpdate struct {
	config
	hooks    []Hook
	mutation *AccountProxyBindingMutation
}

// Where appends a list predicates to the AccountProxyBindingUpdate builder.
func (_u *AccountProxyBindingUpdate) Where(ps ...predicate.AccountProxyBinding) *AccountProxyBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountProxyBindingUpdate) SetAccountID(v int64) *AccountProxyBindingUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountProxyBindingUpdate) SetNillableAccountID(v *int64) *AccountProxyBindingUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *AccountProxyBindingUpdate) SetProxyID(v int64) *AccountProxyBindingUpdate {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *AccountProxyBindingUpdate) SetNillableProxyID(v *int64) *AccountProxyBindingUpdate {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *AccountProxyBindingUpdate) SetPosition(v int) *AccountProxyBindingUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *AccountProxyBindingUpdate) SetNillablePosition(v *int) *AccountProxyBindingUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *AccountProxyBindingUpdate) AddPosition(v int) *AccountProxyBindingUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountProxyBindingUpdate) SetAccount(v *Account) *AccountProxyBindingUpdate {
	return _u.SetAccountID(v.ID)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *AccountProxyBindingUpdate) SetProxy(v *Proxy) *AccountProxyBindingUpdate {
	return _u.SetProxyID(v.ID)
}

// Mutation returns the AccountProxyBindingMutation object of the builder.
func (_u *AccountProxyBindingUpdate) Mutation() *AccountProxyBindingMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountProxyBindingUpdate) ClearAccount() *AccountProxyBindingUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *AccountProxyBindingUpdate) ClearProxy() *AccountProxyBindingUpdate {
	_u.mutation.ClearProxy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountProxyBindingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountProxyBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountProxyBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountProxyBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountProxyBindingUpdate) check() error {
	if v, ok := _u.mutation.Position(); ok {
		if err := accountproxybinding.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "AccountProxyBinding.position": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountProxyBinding.account"`)
	}
	if _u.mutation.ProxyCleared() && len(_u.mutation.ProxyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountProxyBinding.proxy"`)
	}
	return nil
}

func (_u *AccountProxyBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountproxybinding.Table, accountproxybinding.Columns, sqlgraph.NewFieldSpec(accountproxybinding.FieldAccountID, field.TypeInt64), sqlgraph.NewFieldSpec(accountproxybinding.FieldProxyID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(accountproxybinding.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(accountproxybinding.FieldPosition, field.TypeInt, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountproxybinding.AccountTable,
			Columns: []string{accountproxybinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountproxybinding.AccountTable,
			Columns: []string{accountproxybinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountproxybinding.ProxyTable,
			Columns: []string{accountproxybinding.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountproxybinding.ProxyTable,
			Columns: []string{accountproxybinding.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountproxybinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountProxyBindingUpdateOne is the builder for updating a single AccountProxyBinding entity.
type AccountProxyBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountProxyBindingMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountProxyBindingUpdateOne) SetAccountID(v int64) *AccountProxyBindingUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountProxyBindingUpdateOne) SetNillableAccountID(v *int64) *AccountProxyBindingUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetProxyID sets the "proxy_id" field.
func (_u *AccountProxyBindingUpdateOne) SetProxyID(v int64) *AccountProxyBindingUpdateOne {
	_u.mutation.SetProxyID(v)
	return _u
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_u *AccountProxyBindingUpdateOne) SetNillableProxyID(v *int64) *AccountProxyBindingUpdateOne {
	if v != nil {
		_u.SetProxyID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *AccountProxyBindingUpdateOne) SetPosition(v int) *AccountProxyBindingUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *AccountProxyBindingUpdateOne) SetNillablePosition(v *int) *AccountProxyBindingUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *AccountProxyBindingUpdateOne) AddPosition(v int) *AccountProxyBindingUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *AccountProxyBindingUpdateOne) SetAccount(v *Account) *AccountProxyBindingUpdateOne {
	return _u.SetAccountID(v.ID)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_u *AccountProxyBindingUpdateOne) SetProxy(v *Proxy) *AccountProxyBindingUpdateOne {
	return _u.SetProxyID(v.ID)
}

// Mutation returns the AccountProxyBindingMutation object of the builder.
func (_u *AccountProxyBindingUpdateOne) Mutation() *AccountProxyBindingMutation {
	return _u.mutation
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *AccountProxyBindingUpdateOne) ClearAccount() *AccountProxyBindingUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// ClearProxy clears the "proxy" edge to the Proxy entity.
func (_u *AccountProxyBindingUpdateOne) ClearProxy() *AccountProxyBindingUpdateOne {
	_u.mutation.ClearProxy()
	return _u
}

// Where appends a list predicates to the AccountProxyBindingUpdate builder.
func (_u *AccountProxyBindingUpdateOne) Where(ps ...predicate.AccountProxyBinding) *AccountProxyBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountProxyBindingUpdateOne) Select(field string, fields ...string) *AccountProxyBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountProxyBinding entity.
func (_u *AccountProxyBindingUpdateOne) Save(ctx context.Context) (*AccountProxyBinding, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountProxyBindingUpdateOne) SaveX(ctx context.Context) *AccountProxyBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountProxyBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountProxyBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountProxyBindingUpdateOne) check() error {
	if v, ok := _u.mutation.Position(); ok {
		if err := accountproxybinding.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "AccountProxyBinding.position": %w`, err)}
		}
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountProxyBinding.account"`)
	}
	if _u.mutation.ProxyCleared() && len(_u.mutation.ProxyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AccountProxyBinding.proxy"`)
	}
	return nil
}

func (_u *AccountProxyBindingUpdateOne) sqlSave(ctx context.Context) (_node *AccountProxyBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountproxybinding.Table, accountproxybinding.Columns, sqlgraph.NewFieldSpec(accountproxybinding.FieldAccountID, field.TypeInt64), sqlgraph.NewFieldSpec(accountproxybinding.FieldProxyID, field.TypeInt64))
	if id, ok := _u.mutation.AccountID(); !ok {
		return nil, &ValidationError{Name: "account_id", err: errors.New(`ent: missing "AccountProxyBinding.account_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.ProxyID(); !ok {
		return nil, &ValidationError{Name: "proxy_id", err: errors.New(`ent: missing "AccountProxyBinding.proxy_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !accountproxybinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(accountproxybinding.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(accountproxybinding.FieldPosition, field.TypeInt, value)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountproxybinding.AccountTable,
			Columns: []string{accountproxybinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountproxybinding.AccountTable,
			Columns: []string{accountproxybinding.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountproxybinding.ProxyTable,
			Columns: []string{accountproxybinding.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   accountproxybinding.ProxyTable,
			Columns: []string{accountproxybinding.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AccountProxyBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountproxybinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
