// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/proxyipgroup"
	"github.com/Wei-Shaw/sub2api/ent/proxyipgroupmember"
)

// ProxyIPGroupMember is the model entity for the ProxyIPGroupMember schema.
type ProxyIPGroupMember struct {
	config `json:"-"`
	// ProxyIPGroupID holds the value of the "proxy_ip_group_id" field.
	ProxyIPGroupID int64 `json:"proxy_ip_group_id,omitempty"`
	// ProxyID holds the value of the "proxy_id" field.
	ProxyID int64 `json:"proxy_id,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProxyIPGroupMemberQuery when eager-loading is set.
	Edges        ProxyIPGroupMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProxyIPGroupMemberEdges holds the relations/edges for other nodes in the graph.
type ProxyIPGroupMemberEdges struct {
	// Group holds the value of the group edge.
	Group *ProxyIPGroup `json:"group,omitempty"`
	// Proxy holds the value of the proxy edge.
	Proxy *Proxy `json:"proxy,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProxyIPGroupMemberEdges) GroupOrErr() (*ProxyIPGroup, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: proxyipgroup.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// ProxyOrErr returns the Proxy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProxyIPGroupMemberEdges) ProxyOrErr() (*Proxy, error) {
	if e.Proxy != nil {
		return e.Proxy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: proxy.Label}
	}
	return nil, &NotLoadedError{edge: "proxy"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProxyIPGroupMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxyipgroupmember.FieldProxyIPGroupID, proxyipgroupmember.FieldProxyID, proxyipgroupmember.FieldPosition:
			values[i] = new(sql.NullInt64)
		case proxyipgroupmember.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProxyIPGroupMember fields.
func (_m *ProxyIPGroupMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxyipgroupmember.FieldProxyIPGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_ip_group_id", values[i])
			} else if value.Valid {
				_m.ProxyIPGroupID = value.Int64
			}
		case proxyipgroupmember.FieldProxyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_id", values[i])
			} else if value.Valid {
				_m.ProxyID = value.Int64
			}
		case proxyipgroupmember.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case proxyipgroupmember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProxyIPGroupMember.
// This includes values selected through modifiers, order, etc.
func (_m *ProxyIPGroupMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the ProxyIPGroupMember entity.
func (_m *ProxyIPGroupMember) QueryGroup() *ProxyIPGroupQuery {
	return NewProxyIPGroupMemberClient(_m.config).QueryGroup(_m)
}

// QueryProxy queries the "proxy" edge of the ProxyIPGroupMember entity.
func (_m *ProxyIPGroupMember) QueryProxy() *ProxyQuery {
	return NewProxyIPGroupMemberClient(_m.config).QueryProxy(_m)
}

// Update returns a builder for updating this ProxyIPGroupMember.
// Note that you need to call ProxyIPGroupMember.Unwrap() before calling this method if this ProxyIPGroupMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProxyIPGroupMember) Update() *ProxyIPGroupMemberUpdateOne {
	return NewProxyIPGroupMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProxyIPGroupMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProxyIPGroupMember) Unwrap() *ProxyIPGroupMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProxyIPGroupMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProxyIPGroupMember) String() string {
	var builder strings.Builder
	builder.WriteString("ProxyIPGroupMember(")
	builder.WriteString("proxy_ip_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProxyIPGroupID))
	builder.WriteString(", ")
	builder.WriteString("proxy_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProxyID))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProxyIPGroupMembers is a parsable slice of ProxyIPGroupMember.
type ProxyIPGroupMembers []*ProxyIPGroupMember
