// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsyncrun"
)

// UpstreamSyncRun is the model entity for the UpstreamSyncRun schema.
type UpstreamSyncRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Trigger holds the value of the "trigger" field.
	Trigger string `json:"trigger,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// TotalConfigs holds the value of the "total_configs" field.
	TotalConfigs int `json:"total_configs,omitempty"`
	// SuccessConfigs holds the value of the "success_configs" field.
	SuccessConfigs int `json:"success_configs,omitempty"`
	// PartialConfigs holds the value of the "partial_configs" field.
	PartialConfigs int `json:"partial_configs,omitempty"`
	// FailedConfigs holds the value of the "failed_configs" field.
	FailedConfigs int `json:"failed_configs,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamSyncRunQuery when eager-loading is set.
	Edges        UpstreamSyncRunEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamSyncRunEdges holds the relations/edges for other nodes in the graph.
type UpstreamSyncRunEdges struct {
	// Results holds the value of the results edge.
	Results []*UpstreamSyncResult `json:"results,omitempty"`
	// Events holds the value of the events edge.
	Events []*UpstreamEvent `json:"events,omitempty"`
	// BalanceSnapshots holds the value of the balance_snapshots edge.
	BalanceSnapshots []*UpstreamBalanceSnapshot `json:"balance_snapshots,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ResultsOrErr returns the Results value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamSyncRunEdges) ResultsOrErr() ([]*UpstreamSyncResult, error) {
	if e.loadedTypes[0] {
		return e.Results, nil
	}
	return nil, &NotLoadedError{edge: "results"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamSyncRunEdges) EventsOrErr() ([]*UpstreamEvent, error) {
	if e.loadedTypes[1] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// BalanceSnapshotsOrErr returns the BalanceSnapshots value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamSyncRunEdges) BalanceSnapshotsOrErr() ([]*UpstreamBalanceSnapshot, error) {
	if e.loadedTypes[2] {
		return e.BalanceSnapshots, nil
	}
	return nil, &NotLoadedError{edge: "balance_snapshots"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamSyncRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamsyncrun.FieldID, upstreamsyncrun.FieldTotalConfigs, upstreamsyncrun.FieldSuccessConfigs, upstreamsyncrun.FieldPartialConfigs, upstreamsyncrun.FieldFailedConfigs:
			values[i] = new(sql.NullInt64)
		case upstreamsyncrun.FieldTrigger, upstreamsyncrun.FieldStatus:
			values[i] = new(sql.NullString)
		case upstreamsyncrun.FieldStartedAt, upstreamsyncrun.FieldFinishedAt, upstreamsyncrun.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamSyncRun fields.
func (_m *UpstreamSyncRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamsyncrun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamsyncrun.FieldTrigger:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger", values[i])
			} else if value.Valid {
				_m.Trigger = value.String
			}
		case upstreamsyncrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case upstreamsyncrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case upstreamsyncrun.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case upstreamsyncrun.FieldTotalConfigs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_configs", values[i])
			} else if value.Valid {
				_m.TotalConfigs = int(value.Int64)
			}
		case upstreamsyncrun.FieldSuccessConfigs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field success_configs", values[i])
			} else if value.Valid {
				_m.SuccessConfigs = int(value.Int64)
			}
		case upstreamsyncrun.FieldPartialConfigs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field partial_configs", values[i])
			} else if value.Valid {
				_m.PartialConfigs = int(value.Int64)
			}
		case upstreamsyncrun.FieldFailedConfigs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failed_configs", values[i])
			} else if value.Valid {
				_m.FailedConfigs = int(value.Int64)
			}
		case upstreamsyncrun.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamSyncRun.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamSyncRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryResults queries the "results" edge of the UpstreamSyncRun entity.
func (_m *UpstreamSyncRun) QueryResults() *UpstreamSyncResultQuery {
	return NewUpstreamSyncRunClient(_m.config).QueryResults(_m)
}

// QueryEvents queries the "events" edge of the UpstreamSyncRun entity.
func (_m *UpstreamSyncRun) QueryEvents() *UpstreamEventQuery {
	return NewUpstreamSyncRunClient(_m.config).QueryEvents(_m)
}

// QueryBalanceSnapshots queries the "balance_snapshots" edge of the UpstreamSyncRun entity.
func (_m *UpstreamSyncRun) QueryBalanceSnapshots() *UpstreamBalanceSnapshotQuery {
	return NewUpstreamSyncRunClient(_m.config).QueryBalanceSnapshots(_m)
}

// Update returns a builder for updating this UpstreamSyncRun.
// Note that you need to call UpstreamSyncRun.Unwrap() before calling this method if this UpstreamSyncRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamSyncRun) Update() *UpstreamSyncRunUpdateOne {
	return NewUpstreamSyncRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamSyncRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamSyncRun) Unwrap() *UpstreamSyncRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamSyncRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamSyncRun) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamSyncRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("trigger=")
	builder.WriteString(_m.Trigger)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("total_configs=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalConfigs))
	builder.WriteString(", ")
	builder.WriteString("success_configs=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuccessConfigs))
	builder.WriteString(", ")
	builder.WriteString("partial_configs=")
	builder.WriteString(fmt.Sprintf("%v", _m.PartialConfigs))
	builder.WriteString(", ")
	builder.WriteString("failed_configs=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailedConfigs))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamSyncRuns is a parsable slice of UpstreamSyncRun.
type UpstreamSyncRuns []*UpstreamSyncRun
