// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamkey"
	"github.com/Wei-Shaw/sub2api/ent/upstreamkeymodelroute"
)

// UpstreamKeyModelRouteCreate is the builder for creating a UpstreamKeyModelRoute entity.
type UpstreamKeyModelRouteCreate struct {
	config
	mutation *UpstreamKeyModelRouteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamKeyModelRouteCreate) SetCreatedAt(v time.Time) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillableCreatedAt(v *time.Time) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamKeyModelRouteCreate) SetUpdatedAt(v time.Time) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UpstreamKeyModelRouteCreate) SetDeletedAt(v time.Time) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillableDeletedAt(v *time.Time) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUpstreamKeyID sets the "upstream_key_id" field.
func (_c *UpstreamKeyModelRouteCreate) SetUpstreamKeyID(v int64) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetUpstreamKeyID(v)
	return _c
}

// SetPublicModel sets the "public_model" field.
func (_c *UpstreamKeyModelRouteCreate) SetPublicModel(v string) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetPublicModel(v)
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *UpstreamKeyModelRouteCreate) SetUpstreamModel(v string) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillableUpstreamModel(v *string) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetUpstreamModel(*v)
	}
	return _c
}

// SetTargetPlatform sets the "target_platform" field.
func (_c *UpstreamKeyModelRouteCreate) SetTargetPlatform(v string) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetTargetPlatform(v)
	return _c
}

// SetNillableTargetPlatform sets the "target_platform" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillableTargetPlatform(v *string) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetTargetPlatform(*v)
	}
	return _c
}

// SetAPIProtocol sets the "api_protocol" field.
func (_c *UpstreamKeyModelRouteCreate) SetAPIProtocol(v string) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetAPIProtocol(v)
	return _c
}

// SetNillableAPIProtocol sets the "api_protocol" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillableAPIProtocol(v *string) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetAPIProtocol(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *UpstreamKeyModelRouteCreate) SetSource(v string) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillableSource(v *string) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UpstreamKeyModelRouteCreate) SetEnabled(v bool) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillableEnabled(v *bool) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *UpstreamKeyModelRouteCreate) SetPriority(v int) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillablePriority(v *int) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UpstreamKeyModelRouteCreate) SetStatus(v string) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillableStatus(v *string) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *UpstreamKeyModelRouteCreate) SetLastSeenAt(v time.Time) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillableLastSeenAt(v *time.Time) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *UpstreamKeyModelRouteCreate) SetLastError(v string) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *UpstreamKeyModelRouteCreate) SetNillableLastError(v *string) *UpstreamKeyModelRouteCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetKeyID sets the "key" edge to the UpstreamKey entity by ID.
func (_c *UpstreamKeyModelRouteCreate) SetKeyID(id int64) *UpstreamKeyModelRouteCreate {
	_c.mutation.SetKeyID(id)
	return _c
}

// SetKey sets the "key" edge to the UpstreamKey entity.
func (_c *UpstreamKeyModelRouteCreate) SetKey(v *UpstreamKey) *UpstreamKeyModelRouteCreate {
	return _c.SetKeyID(v.ID)
}

// Mutation returns the UpstreamKeyModelRouteMutation object of the builder.
func (_c *UpstreamKeyModelRouteCreate) Mutation() *UpstreamKeyModelRouteMutation {
	return _c.mutation
}

// Save creates the UpstreamKeyModelRoute in the database.
func (_c *UpstreamKeyModelRouteCreate) Save(ctx context.Context) (*UpstreamKeyModelRoute, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamKeyModelRouteCreate) SaveX(ctx context.Context) *UpstreamKeyModelRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamKeyModelRouteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamKeyModelRouteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamKeyModelRouteCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if upstreamkeymodelroute.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamkeymodelroute.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamkeymodelroute.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if upstreamkeymodelroute.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamkeymodelroute.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamkeymodelroute.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		v := upstreamkeymodelroute.DefaultUpstreamModel
		_c.mutation.SetUpstreamModel(v)
	}
	if _, ok := _c.mutation.TargetPlatform(); !ok {
		v := upstreamkeymodelroute.DefaultTargetPlatform
		_c.mutation.SetTargetPlatform(v)
	}
	if _, ok := _c.mutation.APIProtocol(); !ok {
		v := upstreamkeymodelroute.DefaultAPIProtocol
		_c.mutation.SetAPIProtocol(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := upstreamkeymodelroute.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := upstreamkeymodelroute.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := upstreamkeymodelroute.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := upstreamkeymodelroute.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamKeyModelRouteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamKeyModelRoute.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamKeyModelRoute.updated_at"`)}
	}
	if _, ok := _c.mutation.UpstreamKeyID(); !ok {
		return &ValidationError{Name: "upstream_key_id", err: errors.New(`ent: missing required field "UpstreamKeyModelRoute.upstream_key_id"`)}
	}
	if _, ok := _c.mutation.PublicModel(); !ok {
		return &ValidationError{Name: "public_model", err: errors.New(`ent: missing required field "UpstreamKeyModelRoute.public_model"`)}
	}
	if v, ok := _c.mutation.PublicModel(); ok {
		if err := upstreamkeymodelroute.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "UpstreamKeyModelRoute.public_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "UpstreamKeyModelRoute.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := upstreamkeymodelroute.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "UpstreamKeyModelRoute.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetPlatform(); !ok {
		return &ValidationError{Name: "target_platform", err: errors.New(`ent: missing required field "UpstreamKeyModelRoute.target_platform"`)}
	}
	if v, ok := _c.mutation.TargetPlatform(); ok {
		if err := upstreamkeymodelroute.TargetPlatformValidator(v); err != nil {
			return &ValidationError{Name: "target_platform", err: fmt.Errorf(`ent: validator failed for field "UpstreamKeyModelRoute.target_platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIProtocol(); !ok {
		return &ValidationError{Name: "api_protocol", err: errors.New(`ent: missing required field "UpstreamKeyModelRoute.api_protocol"`)}
	}
	if v, ok := _c.mutation.APIProtocol(); ok {
		if err := upstreamkeymodelroute.APIProtocolValidator(v); err != nil {
			return &ValidationError{Name: "api_protocol", err: fmt.Errorf(`ent: validator failed for field "UpstreamKeyModelRoute.api_protocol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "UpstreamKeyModelRoute.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := upstreamkeymodelroute.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "UpstreamKeyModelRoute.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UpstreamKeyModelRoute.enabled"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "UpstreamKeyModelRoute.priority"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UpstreamKeyModelRoute.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := upstreamkeymodelroute.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamKeyModelRoute.status": %w`, err)}
		}
	}
	if len(_c.mutation.KeyIDs()) == 0 {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required edge "UpstreamKeyModelRoute.key"`)}
	}
	return nil
}

func (_c *UpstreamKeyModelRouteCreate) sqlSave(ctx context.Context) (*UpstreamKeyModelRoute, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamKeyModelRouteCreate) createSpec() (*UpstreamKeyModelRoute, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamKeyModelRoute{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamkeymodelroute.Table, sqlgraph.NewFieldSpec(upstreamkeymodelroute.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.PublicModel(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldPublicModel, field.TypeString, value)
		_node.PublicModel = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.TargetPlatform(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldTargetPlatform, field.TypeString, value)
		_node.TargetPlatform = value
	}
	if value, ok := _c.mutation.APIProtocol(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldAPIProtocol, field.TypeString, value)
		_node.APIProtocol = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(upstreamkeymodelroute.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if nodes := _c.mutation.KeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamkeymodelroute.KeyTable,
			Columns: []string{upstreamkeymodelroute.KeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamkey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UpstreamKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamKeyModelRoute.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamKeyModelRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamKeyModelRouteCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamKeyModelRouteUpsertOne {
	_c.conflict = opts
	return &UpstreamKeyModelRouteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamKeyModelRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamKeyModelRouteCreate) OnConflictColumns(columns ...string) *UpstreamKeyModelRouteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamKeyModelRouteUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamKeyModelRouteUpsertOne is the builder for "upsert"-ing
	//  one UpstreamKeyModelRoute node.
	UpstreamKeyModelRouteUpsertOne struct {
		create *UpstreamKeyModelRouteCreate
	}

	// UpstreamKeyModelRouteUpsert is the "OnConflict" setter.
	UpstreamKeyModelRouteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamKeyModelRouteUpsert) SetUpdatedAt(v time.Time) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdateUpdatedAt() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamKeyModelRouteUpsert) SetDeletedAt(v time.Time) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdateDeletedAt() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamKeyModelRouteUpsert) ClearDeletedAt() *UpstreamKeyModelRouteUpsert {
	u.SetNull(upstreamkeymodelroute.FieldDeletedAt)
	return u
}

// SetUpstreamKeyID sets the "upstream_key_id" field.
func (u *UpstreamKeyModelRouteUpsert) SetUpstreamKeyID(v int64) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldUpstreamKeyID, v)
	return u
}

// UpdateUpstreamKeyID sets the "upstream_key_id" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdateUpstreamKeyID() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldUpstreamKeyID)
	return u
}

// SetPublicModel sets the "public_model" field.
func (u *UpstreamKeyModelRouteUpsert) SetPublicModel(v string) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldPublicModel, v)
	return u
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdatePublicModel() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldPublicModel)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *UpstreamKeyModelRouteUpsert) SetUpstreamModel(v string) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdateUpstreamModel() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldUpstreamModel)
	return u
}

// SetTargetPlatform sets the "target_platform" field.
func (u *UpstreamKeyModelRouteUpsert) SetTargetPlatform(v string) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldTargetPlatform, v)
	return u
}

// UpdateTargetPlatform sets the "target_platform" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdateTargetPlatform() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldTargetPlatform)
	return u
}

// SetAPIProtocol sets the "api_protocol" field.
func (u *UpstreamKeyModelRouteUpsert) SetAPIProtocol(v string) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldAPIProtocol, v)
	return u
}

// UpdateAPIProtocol sets the "api_protocol" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdateAPIProtocol() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldAPIProtocol)
	return u
}

// SetSource sets the "source" field.
func (u *UpstreamKeyModelRouteUpsert) SetSource(v string) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdateSource() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldSource)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamKeyModelRouteUpsert) SetEnabled(v bool) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdateEnabled() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldEnabled)
	return u
}

// SetPriority sets the "priority" field.
func (u *UpstreamKeyModelRouteUpsert) SetPriority(v int) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdatePriority() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *UpstreamKeyModelRouteUpsert) AddPriority(v int) *UpstreamKeyModelRouteUpsert {
	u.Add(upstreamkeymodelroute.FieldPriority, v)
	return u
}

// SetStatus sets the "status" field.
func (u *UpstreamKeyModelRouteUpsert) SetStatus(v string) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdateStatus() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldStatus)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *UpstreamKeyModelRouteUpsert) SetLastSeenAt(v time.Time) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdateLastSeenAt() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldLastSeenAt)
	return u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *UpstreamKeyModelRouteUpsert) ClearLastSeenAt() *UpstreamKeyModelRouteUpsert {
	u.SetNull(upstreamkeymodelroute.FieldLastSeenAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *UpstreamKeyModelRouteUpsert) SetLastError(v string) *UpstreamKeyModelRouteUpsert {
	u.Set(upstreamkeymodelroute.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsert) UpdateLastError() *UpstreamKeyModelRouteUpsert {
	u.SetExcluded(upstreamkeymodelroute.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamKeyModelRouteUpsert) ClearLastError() *UpstreamKeyModelRouteUpsert {
	u.SetNull(upstreamkeymodelroute.FieldLastError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamKeyModelRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamKeyModelRouteUpsertOne) UpdateNewValues() *UpstreamKeyModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamkeymodelroute.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamKeyModelRoute.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamKeyModelRouteUpsertOne) Ignore() *UpstreamKeyModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamKeyModelRouteUpsertOne) DoNothing() *UpstreamKeyModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamKeyModelRouteCreate.OnConflict
// documentation for more info.
func (u *UpstreamKeyModelRouteUpsertOne) Update(set func(*UpstreamKeyModelRouteUpsert)) *UpstreamKeyModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamKeyModelRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetUpdatedAt(v time.Time) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdateUpdatedAt() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetDeletedAt(v time.Time) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdateDeletedAt() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamKeyModelRouteUpsertOne) ClearDeletedAt() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpstreamKeyID sets the "upstream_key_id" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetUpstreamKeyID(v int64) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetUpstreamKeyID(v)
	})
}

// UpdateUpstreamKeyID sets the "upstream_key_id" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdateUpstreamKeyID() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateUpstreamKeyID()
	})
}

// SetPublicModel sets the "public_model" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetPublicModel(v string) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetPublicModel(v)
	})
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdatePublicModel() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdatePublicModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetUpstreamModel(v string) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdateUpstreamModel() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetTargetPlatform sets the "target_platform" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetTargetPlatform(v string) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetTargetPlatform(v)
	})
}

// UpdateTargetPlatform sets the "target_platform" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdateTargetPlatform() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateTargetPlatform()
	})
}

// SetAPIProtocol sets the "api_protocol" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetAPIProtocol(v string) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetAPIProtocol(v)
	})
}

// UpdateAPIProtocol sets the "api_protocol" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdateAPIProtocol() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateAPIProtocol()
	})
}

// SetSource sets the "source" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetSource(v string) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdateSource() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateSource()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetEnabled(v bool) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdateEnabled() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetPriority(v int) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *UpstreamKeyModelRouteUpsertOne) AddPriority(v int) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdatePriority() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdatePriority()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetStatus(v string) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdateStatus() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateStatus()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetLastSeenAt(v time.Time) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdateLastSeenAt() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *UpstreamKeyModelRouteUpsertOne) ClearLastSeenAt() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *UpstreamKeyModelRouteUpsertOne) SetLastError(v string) *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertOne) UpdateLastError() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamKeyModelRouteUpsertOne) ClearLastError() *UpstreamKeyModelRouteUpsertOne {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.ClearLastError()
	})
}

// Exec executes the query.
func (u *UpstreamKeyModelRouteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamKeyModelRouteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamKeyModelRouteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamKeyModelRouteUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamKeyModelRouteUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamKeyModelRouteCreateBulk is the builder for creating many UpstreamKeyModelRoute entities in bulk.
type UpstreamKeyModelRouteCreateBulk struct {
	config
	err      error
	builders []*UpstreamKeyModelRouteCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamKeyModelRoute entities in the database.
func (_c *UpstreamKeyModelRouteCreateBulk) Save(ctx context.Context) ([]*UpstreamKeyModelRoute, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamKeyModelRoute, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamKeyModelRouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamKeyModelRouteCreateBulk) SaveX(ctx context.Context) []*UpstreamKeyModelRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamKeyModelRouteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamKeyModelRouteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamKeyModelRoute.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamKeyModelRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamKeyModelRouteCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamKeyModelRouteUpsertBulk {
	_c.conflict = opts
	return &UpstreamKeyModelRouteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamKeyModelRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamKeyModelRouteCreateBulk) OnConflictColumns(columns ...string) *UpstreamKeyModelRouteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamKeyModelRouteUpsertBulk{
		create: _c,
	}
}

// UpstreamKeyModelRouteUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamKeyModelRoute nodes.
type UpstreamKeyModelRouteUpsertBulk struct {
	create *UpstreamKeyModelRouteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamKeyModelRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateNewValues() *UpstreamKeyModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamkeymodelroute.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamKeyModelRoute.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamKeyModelRouteUpsertBulk) Ignore() *UpstreamKeyModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamKeyModelRouteUpsertBulk) DoNothing() *UpstreamKeyModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamKeyModelRouteCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamKeyModelRouteUpsertBulk) Update(set func(*UpstreamKeyModelRouteUpsert)) *UpstreamKeyModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamKeyModelRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateUpdatedAt() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetDeletedAt(v time.Time) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateDeletedAt() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamKeyModelRouteUpsertBulk) ClearDeletedAt() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUpstreamKeyID sets the "upstream_key_id" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetUpstreamKeyID(v int64) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetUpstreamKeyID(v)
	})
}

// UpdateUpstreamKeyID sets the "upstream_key_id" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateUpstreamKeyID() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateUpstreamKeyID()
	})
}

// SetPublicModel sets the "public_model" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetPublicModel(v string) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetPublicModel(v)
	})
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdatePublicModel() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdatePublicModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetUpstreamModel(v string) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateUpstreamModel() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetTargetPlatform sets the "target_platform" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetTargetPlatform(v string) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetTargetPlatform(v)
	})
}

// UpdateTargetPlatform sets the "target_platform" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateTargetPlatform() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateTargetPlatform()
	})
}

// SetAPIProtocol sets the "api_protocol" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetAPIProtocol(v string) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetAPIProtocol(v)
	})
}

// UpdateAPIProtocol sets the "api_protocol" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateAPIProtocol() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateAPIProtocol()
	})
}

// SetSource sets the "source" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetSource(v string) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateSource() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateSource()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetEnabled(v bool) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateEnabled() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateEnabled()
	})
}

// SetPriority sets the "priority" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetPriority(v int) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *UpstreamKeyModelRouteUpsertBulk) AddPriority(v int) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdatePriority() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdatePriority()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetStatus(v string) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateStatus() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateStatus()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetLastSeenAt(v time.Time) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateLastSeenAt() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateLastSeenAt()
	})
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (u *UpstreamKeyModelRouteUpsertBulk) ClearLastSeenAt() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.ClearLastSeenAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *UpstreamKeyModelRouteUpsertBulk) SetLastError(v string) *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamKeyModelRouteUpsertBulk) UpdateLastError() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamKeyModelRouteUpsertBulk) ClearLastError() *UpstreamKeyModelRouteUpsertBulk {
	return u.Update(func(s *UpstreamKeyModelRouteUpsert) {
		s.ClearLastError()
	})
}

// Exec executes the query.
func (u *UpstreamKeyModelRouteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamKeyModelRouteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamKeyModelRouteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamKeyModelRouteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
