// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconfig"
	"github.com/Wei-Shaw/sub2api/ent/upstreamkey"
)

// UpstreamConfigCreate is the builder for creating a UpstreamConfig entity.
type UpstreamConfigCreate struct {
	config
	mutation *UpstreamConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamConfigCreate) SetCreatedAt(v time.Time) *UpstreamConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamConfigCreate) SetNillableCreatedAt(v *time.Time) *UpstreamConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamConfigCreate) SetUpdatedAt(v time.Time) *UpstreamConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamConfigCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UpstreamConfigCreate) SetDeletedAt(v time.Time) *UpstreamConfigCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UpstreamConfigCreate) SetNillableDeletedAt(v *time.Time) *UpstreamConfigCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UpstreamConfigCreate) SetName(v string) *UpstreamConfigCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *UpstreamConfigCreate) SetProvider(v string) *UpstreamConfigCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *UpstreamConfigCreate) SetBaseURL(v string) *UpstreamConfigCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetAuthMode sets the "auth_mode" field.
func (_c *UpstreamConfigCreate) SetAuthMode(v string) *UpstreamConfigCreate {
	_c.mutation.SetAuthMode(v)
	return _c
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_c *UpstreamConfigCreate) SetNillableAuthMode(v *string) *UpstreamConfigCreate {
	if v != nil {
		_c.SetAuthMode(*v)
	}
	return _c
}

// SetCredentials sets the "credentials" field.
func (_c *UpstreamConfigCreate) SetCredentials(v map[string]interface{}) *UpstreamConfigCreate {
	_c.mutation.SetCredentials(v)
	return _c
}

// SetExtra sets the "extra" field.
func (_c *UpstreamConfigCreate) SetExtra(v map[string]interface{}) *UpstreamConfigCreate {
	_c.mutation.SetExtra(v)
	return _c
}

// SetProxyID sets the "proxy_id" field.
func (_c *UpstreamConfigCreate) SetProxyID(v int64) *UpstreamConfigCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_c *UpstreamConfigCreate) SetNillableProxyID(v *int64) *UpstreamConfigCreate {
	if v != nil {
		_c.SetProxyID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UpstreamConfigCreate) SetStatus(v string) *UpstreamConfigCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UpstreamConfigCreate) SetNillableStatus(v *string) *UpstreamConfigCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *UpstreamConfigCreate) SetLastError(v string) *UpstreamConfigCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *UpstreamConfigCreate) SetNillableLastError(v *string) *UpstreamConfigCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *UpstreamConfigCreate) SetLastCheckedAt(v time.Time) *UpstreamConfigCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *UpstreamConfigCreate) SetNillableLastCheckedAt(v *time.Time) *UpstreamConfigCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetLastSuccessAt sets the "last_success_at" field.
func (_c *UpstreamConfigCreate) SetLastSuccessAt(v time.Time) *UpstreamConfigCreate {
	_c.mutation.SetLastSuccessAt(v)
	return _c
}

// SetNillableLastSuccessAt sets the "last_success_at" field if the given value is not nil.
func (_c *UpstreamConfigCreate) SetNillableLastSuccessAt(v *time.Time) *UpstreamConfigCreate {
	if v != nil {
		_c.SetLastSuccessAt(*v)
	}
	return _c
}

// AddKeyIDs adds the "keys" edge to the UpstreamKey entity by IDs.
func (_c *UpstreamConfigCreate) AddKeyIDs(ids ...int64) *UpstreamConfigCreate {
	_c.mutation.AddKeyIDs(ids...)
	return _c
}

// AddKeys adds the "keys" edges to the UpstreamKey entity.
func (_c *UpstreamConfigCreate) AddKeys(v ...*UpstreamKey) *UpstreamConfigCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddKeyIDs(ids...)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *UpstreamConfigCreate) AddAccountIDs(ids ...int64) *UpstreamConfigCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *UpstreamConfigCreate) AddAccounts(v ...*Account) *UpstreamConfigCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_c *UpstreamConfigCreate) SetProxy(v *Proxy) *UpstreamConfigCreate {
	return _c.SetProxyID(v.ID)
}

// Mutation returns the UpstreamConfigMutation object of the builder.
func (_c *UpstreamConfigCreate) Mutation() *UpstreamConfigMutation {
	return _c.mutation
}

// Save creates the UpstreamConfig in the database.
func (_c *UpstreamConfigCreate) Save(ctx context.Context) (*UpstreamConfig, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamConfigCreate) SaveX(ctx context.Context) *UpstreamConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamConfigCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if upstreamconfig.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamconfig.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if upstreamconfig.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized upstreamconfig.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := upstreamconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AuthMode(); !ok {
		v := upstreamconfig.DefaultAuthMode
		_c.mutation.SetAuthMode(v)
	}
	if _, ok := _c.mutation.Credentials(); !ok {
		if upstreamconfig.DefaultCredentials == nil {
			return fmt.Errorf("ent: uninitialized upstreamconfig.DefaultCredentials (forgotten import ent/runtime?)")
		}
		v := upstreamconfig.DefaultCredentials()
		_c.mutation.SetCredentials(v)
	}
	if _, ok := _c.mutation.Extra(); !ok {
		if upstreamconfig.DefaultExtra == nil {
			return fmt.Errorf("ent: uninitialized upstreamconfig.DefaultExtra (forgotten import ent/runtime?)")
		}
		v := upstreamconfig.DefaultExtra()
		_c.mutation.SetExtra(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := upstreamconfig.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamConfigCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamConfig.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpstreamConfig.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := upstreamconfig.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamConfig.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "UpstreamConfig.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := upstreamconfig.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UpstreamConfig.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "UpstreamConfig.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := upstreamconfig.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamConfig.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthMode(); !ok {
		return &ValidationError{Name: "auth_mode", err: errors.New(`ent: missing required field "UpstreamConfig.auth_mode"`)}
	}
	if v, ok := _c.mutation.AuthMode(); ok {
		if err := upstreamconfig.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "UpstreamConfig.auth_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Credentials(); !ok {
		return &ValidationError{Name: "credentials", err: errors.New(`ent: missing required field "UpstreamConfig.credentials"`)}
	}
	if _, ok := _c.mutation.Extra(); !ok {
		return &ValidationError{Name: "extra", err: errors.New(`ent: missing required field "UpstreamConfig.extra"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UpstreamConfig.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := upstreamconfig.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamConfig.status": %w`, err)}
		}
	}
	return nil
}

func (_c *UpstreamConfigCreate) sqlSave(ctx context.Context) (*UpstreamConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamConfigCreate) createSpec() (*UpstreamConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamconfig.Table, sqlgraph.NewFieldSpec(upstreamconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(upstreamconfig.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstreamconfig.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(upstreamconfig.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(upstreamconfig.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.AuthMode(); ok {
		_spec.SetField(upstreamconfig.FieldAuthMode, field.TypeString, value)
		_node.AuthMode = value
	}
	if value, ok := _c.mutation.Credentials(); ok {
		_spec.SetField(upstreamconfig.FieldCredentials, field.TypeJSON, value)
		_node.Credentials = value
	}
	if value, ok := _c.mutation.Extra(); ok {
		_spec.SetField(upstreamconfig.FieldExtra, field.TypeJSON, value)
		_node.Extra = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(upstreamconfig.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(upstreamconfig.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(upstreamconfig.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.LastSuccessAt(); ok {
		_spec.SetField(upstreamconfig.FieldLastSuccessAt, field.TypeTime, value)
		_node.LastSuccessAt = &value
	}
	if nodes := _c.mutation.KeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconfig.KeysTable,
			Columns: []string{upstreamconfig.KeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamkey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconfig.AccountsTable,
			Columns: []string{upstreamconfig.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   upstreamconfig.ProxyTable,
			Columns: []string{upstreamconfig.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProxyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamConfig.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamConfigCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamConfigUpsertOne {
	_c.conflict = opts
	return &UpstreamConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamConfigCreate) OnConflictColumns(columns ...string) *UpstreamConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamConfigUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamConfigUpsertOne is the builder for "upsert"-ing
	//  one UpstreamConfig node.
	UpstreamConfigUpsertOne struct {
		create *UpstreamConfigCreate
	}

	// UpstreamConfigUpsert is the "OnConflict" setter.
	UpstreamConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamConfigUpsert) SetUpdatedAt(v time.Time) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateUpdatedAt() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamConfigUpsert) SetDeletedAt(v time.Time) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateDeletedAt() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamConfigUpsert) ClearDeletedAt() *UpstreamConfigUpsert {
	u.SetNull(upstreamconfig.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *UpstreamConfigUpsert) SetName(v string) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateName() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldName)
	return u
}

// SetProvider sets the "provider" field.
func (u *UpstreamConfigUpsert) SetProvider(v string) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateProvider() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldProvider)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamConfigUpsert) SetBaseURL(v string) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateBaseURL() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldBaseURL)
	return u
}

// SetAuthMode sets the "auth_mode" field.
func (u *UpstreamConfigUpsert) SetAuthMode(v string) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldAuthMode, v)
	return u
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateAuthMode() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldAuthMode)
	return u
}

// SetCredentials sets the "credentials" field.
func (u *UpstreamConfigUpsert) SetCredentials(v map[string]interface{}) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldCredentials, v)
	return u
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateCredentials() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldCredentials)
	return u
}

// SetExtra sets the "extra" field.
func (u *UpstreamConfigUpsert) SetExtra(v map[string]interface{}) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldExtra, v)
	return u
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateExtra() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldExtra)
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *UpstreamConfigUpsert) SetProxyID(v int64) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateProxyID() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldProxyID)
	return u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *UpstreamConfigUpsert) ClearProxyID() *UpstreamConfigUpsert {
	u.SetNull(upstreamconfig.FieldProxyID)
	return u
}

// SetStatus sets the "status" field.
func (u *UpstreamConfigUpsert) SetStatus(v string) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateStatus() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldStatus)
	return u
}

// SetLastError sets the "last_error" field.
func (u *UpstreamConfigUpsert) SetLastError(v string) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateLastError() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamConfigUpsert) ClearLastError() *UpstreamConfigUpsert {
	u.SetNull(upstreamconfig.FieldLastError)
	return u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *UpstreamConfigUpsert) SetLastCheckedAt(v time.Time) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldLastCheckedAt, v)
	return u
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateLastCheckedAt() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldLastCheckedAt)
	return u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *UpstreamConfigUpsert) ClearLastCheckedAt() *UpstreamConfigUpsert {
	u.SetNull(upstreamconfig.FieldLastCheckedAt)
	return u
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *UpstreamConfigUpsert) SetLastSuccessAt(v time.Time) *UpstreamConfigUpsert {
	u.Set(upstreamconfig.FieldLastSuccessAt, v)
	return u
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsert) UpdateLastSuccessAt() *UpstreamConfigUpsert {
	u.SetExcluded(upstreamconfig.FieldLastSuccessAt)
	return u
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *UpstreamConfigUpsert) ClearLastSuccessAt() *UpstreamConfigUpsert {
	u.SetNull(upstreamconfig.FieldLastSuccessAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamConfigUpsertOne) UpdateNewValues() *UpstreamConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamConfigUpsertOne) Ignore() *UpstreamConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamConfigUpsertOne) DoNothing() *UpstreamConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamConfigCreate.OnConflict
// documentation for more info.
func (u *UpstreamConfigUpsertOne) Update(set func(*UpstreamConfigUpsert)) *UpstreamConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamConfigUpsertOne) SetUpdatedAt(v time.Time) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateUpdatedAt() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamConfigUpsertOne) SetDeletedAt(v time.Time) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateDeletedAt() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamConfigUpsertOne) ClearDeletedAt() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamConfigUpsertOne) SetName(v string) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateName() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateName()
	})
}

// SetProvider sets the "provider" field.
func (u *UpstreamConfigUpsertOne) SetProvider(v string) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateProvider() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateProvider()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamConfigUpsertOne) SetBaseURL(v string) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateBaseURL() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateBaseURL()
	})
}

// SetAuthMode sets the "auth_mode" field.
func (u *UpstreamConfigUpsertOne) SetAuthMode(v string) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetAuthMode(v)
	})
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateAuthMode() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateAuthMode()
	})
}

// SetCredentials sets the "credentials" field.
func (u *UpstreamConfigUpsertOne) SetCredentials(v map[string]interface{}) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetCredentials(v)
	})
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateCredentials() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateCredentials()
	})
}

// SetExtra sets the "extra" field.
func (u *UpstreamConfigUpsertOne) SetExtra(v map[string]interface{}) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetExtra(v)
	})
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateExtra() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateExtra()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *UpstreamConfigUpsertOne) SetProxyID(v int64) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateProxyID() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *UpstreamConfigUpsertOne) ClearProxyID() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.ClearProxyID()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamConfigUpsertOne) SetStatus(v string) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateStatus() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *UpstreamConfigUpsertOne) SetLastError(v string) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateLastError() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamConfigUpsertOne) ClearLastError() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.ClearLastError()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *UpstreamConfigUpsertOne) SetLastCheckedAt(v time.Time) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateLastCheckedAt() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *UpstreamConfigUpsertOne) ClearLastCheckedAt() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *UpstreamConfigUpsertOne) SetLastSuccessAt(v time.Time) *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetLastSuccessAt(v)
	})
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsertOne) UpdateLastSuccessAt() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateLastSuccessAt()
	})
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *UpstreamConfigUpsertOne) ClearLastSuccessAt() *UpstreamConfigUpsertOne {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.ClearLastSuccessAt()
	})
}

// Exec executes the query.
func (u *UpstreamConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamConfigCreateBulk is the builder for creating many UpstreamConfig entities in bulk.
type UpstreamConfigCreateBulk struct {
	config
	err      error
	builders []*UpstreamConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamConfig entities in the database.
func (_c *UpstreamConfigCreateBulk) Save(ctx context.Context) ([]*UpstreamConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamConfigCreateBulk) SaveX(ctx context.Context) []*UpstreamConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamConfigUpsertBulk {
	_c.conflict = opts
	return &UpstreamConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamConfigCreateBulk) OnConflictColumns(columns ...string) *UpstreamConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamConfigUpsertBulk{
		create: _c,
	}
}

// UpstreamConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamConfig nodes.
type UpstreamConfigUpsertBulk struct {
	create *UpstreamConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamConfigUpsertBulk) UpdateNewValues() *UpstreamConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamConfigUpsertBulk) Ignore() *UpstreamConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamConfigUpsertBulk) DoNothing() *UpstreamConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamConfigCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamConfigUpsertBulk) Update(set func(*UpstreamConfigUpsert)) *UpstreamConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamConfigUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateUpdatedAt() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UpstreamConfigUpsertBulk) SetDeletedAt(v time.Time) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateDeletedAt() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UpstreamConfigUpsertBulk) ClearDeletedAt() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamConfigUpsertBulk) SetName(v string) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateName() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateName()
	})
}

// SetProvider sets the "provider" field.
func (u *UpstreamConfigUpsertBulk) SetProvider(v string) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateProvider() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateProvider()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamConfigUpsertBulk) SetBaseURL(v string) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateBaseURL() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateBaseURL()
	})
}

// SetAuthMode sets the "auth_mode" field.
func (u *UpstreamConfigUpsertBulk) SetAuthMode(v string) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetAuthMode(v)
	})
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateAuthMode() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateAuthMode()
	})
}

// SetCredentials sets the "credentials" field.
func (u *UpstreamConfigUpsertBulk) SetCredentials(v map[string]interface{}) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetCredentials(v)
	})
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateCredentials() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateCredentials()
	})
}

// SetExtra sets the "extra" field.
func (u *UpstreamConfigUpsertBulk) SetExtra(v map[string]interface{}) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetExtra(v)
	})
}

// UpdateExtra sets the "extra" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateExtra() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateExtra()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *UpstreamConfigUpsertBulk) SetProxyID(v int64) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateProxyID() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *UpstreamConfigUpsertBulk) ClearProxyID() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.ClearProxyID()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamConfigUpsertBulk) SetStatus(v string) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateStatus() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *UpstreamConfigUpsertBulk) SetLastError(v string) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateLastError() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamConfigUpsertBulk) ClearLastError() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.ClearLastError()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *UpstreamConfigUpsertBulk) SetLastCheckedAt(v time.Time) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateLastCheckedAt() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *UpstreamConfigUpsertBulk) ClearLastCheckedAt() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetLastSuccessAt sets the "last_success_at" field.
func (u *UpstreamConfigUpsertBulk) SetLastSuccessAt(v time.Time) *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.SetLastSuccessAt(v)
	})
}

// UpdateLastSuccessAt sets the "last_success_at" field to the value that was provided on create.
func (u *UpstreamConfigUpsertBulk) UpdateLastSuccessAt() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.UpdateLastSuccessAt()
	})
}

// ClearLastSuccessAt clears the value of the "last_success_at" field.
func (u *UpstreamConfigUpsertBulk) ClearLastSuccessAt() *UpstreamConfigUpsertBulk {
	return u.Update(func(s *UpstreamConfigUpsert) {
		s.ClearLastSuccessAt()
	})
}

// Exec executes the query.
func (u *UpstreamConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
