// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconfig"
	"github.com/Wei-Shaw/sub2api/ent/upstreamkey"
	"github.com/Wei-Shaw/sub2api/ent/upstreamkeyratesnapshot"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsyncrun"
)

// UpstreamKeyRateSnapshot is the model entity for the UpstreamKeyRateSnapshot schema.
type UpstreamKeyRateSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UpstreamConfigID holds the value of the "upstream_config_id" field.
	UpstreamConfigID int64 `json:"upstream_config_id,omitempty"`
	// UpstreamKeyID holds the value of the "upstream_key_id" field.
	UpstreamKeyID *int64 `json:"upstream_key_id,omitempty"`
	// RemoteKeyID holds the value of the "remote_key_id" field.
	RemoteKeyID *int64 `json:"remote_key_id,omitempty"`
	// KeyNameSnapshot holds the value of the "key_name_snapshot" field.
	KeyNameSnapshot string `json:"key_name_snapshot,omitempty"`
	// KeyHashSnapshot holds the value of the "key_hash_snapshot" field.
	KeyHashSnapshot string `json:"key_hash_snapshot,omitempty"`
	// SyncRunID holds the value of the "sync_run_id" field.
	SyncRunID *int64 `json:"sync_run_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// RawRateMultiplier holds the value of the "raw_rate_multiplier" field.
	RawRateMultiplier float64 `json:"raw_rate_multiplier,omitempty"`
	// RechargeRate holds the value of the "recharge_rate" field.
	RechargeRate float64 `json:"recharge_rate,omitempty"`
	// EffectiveCostMultiplier holds the value of the "effective_cost_multiplier" field.
	EffectiveCostMultiplier float64 `json:"effective_cost_multiplier,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// ObservedAt holds the value of the "observed_at" field.
	ObservedAt time.Time `json:"observed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamKeyRateSnapshotQuery when eager-loading is set.
	Edges        UpstreamKeyRateSnapshotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamKeyRateSnapshotEdges holds the relations/edges for other nodes in the graph.
type UpstreamKeyRateSnapshotEdges struct {
	// Config holds the value of the config edge.
	Config *UpstreamConfig `json:"config,omitempty"`
	// Key holds the value of the key edge.
	Key *UpstreamKey `json:"key,omitempty"`
	// Run holds the value of the run edge.
	Run *UpstreamSyncRun `json:"run,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ConfigOrErr returns the Config value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamKeyRateSnapshotEdges) ConfigOrErr() (*UpstreamConfig, error) {
	if e.Config != nil {
		return e.Config, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: upstreamconfig.Label}
	}
	return nil, &NotLoadedError{edge: "config"}
}

// KeyOrErr returns the Key value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamKeyRateSnapshotEdges) KeyOrErr() (*UpstreamKey, error) {
	if e.Key != nil {
		return e.Key, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: upstreamkey.Label}
	}
	return nil, &NotLoadedError{edge: "key"}
}

// RunOrErr returns the Run value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamKeyRateSnapshotEdges) RunOrErr() (*UpstreamSyncRun, error) {
	if e.Run != nil {
		return e.Run, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: upstreamsyncrun.Label}
	}
	return nil, &NotLoadedError{edge: "run"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamKeyRateSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamkeyratesnapshot.FieldRawRateMultiplier, upstreamkeyratesnapshot.FieldRechargeRate, upstreamkeyratesnapshot.FieldEffectiveCostMultiplier:
			values[i] = new(sql.NullFloat64)
		case upstreamkeyratesnapshot.FieldID, upstreamkeyratesnapshot.FieldUpstreamConfigID, upstreamkeyratesnapshot.FieldUpstreamKeyID, upstreamkeyratesnapshot.FieldRemoteKeyID, upstreamkeyratesnapshot.FieldSyncRunID:
			values[i] = new(sql.NullInt64)
		case upstreamkeyratesnapshot.FieldKeyNameSnapshot, upstreamkeyratesnapshot.FieldKeyHashSnapshot, upstreamkeyratesnapshot.FieldProvider, upstreamkeyratesnapshot.FieldSource:
			values[i] = new(sql.NullString)
		case upstreamkeyratesnapshot.FieldObservedAt, upstreamkeyratesnapshot.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamKeyRateSnapshot fields.
func (_m *UpstreamKeyRateSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamkeyratesnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamkeyratesnapshot.FieldUpstreamConfigID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_config_id", values[i])
			} else if value.Valid {
				_m.UpstreamConfigID = value.Int64
			}
		case upstreamkeyratesnapshot.FieldUpstreamKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_key_id", values[i])
			} else if value.Valid {
				_m.UpstreamKeyID = new(int64)
				*_m.UpstreamKeyID = value.Int64
			}
		case upstreamkeyratesnapshot.FieldRemoteKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field remote_key_id", values[i])
			} else if value.Valid {
				_m.RemoteKeyID = new(int64)
				*_m.RemoteKeyID = value.Int64
			}
		case upstreamkeyratesnapshot.FieldKeyNameSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_name_snapshot", values[i])
			} else if value.Valid {
				_m.KeyNameSnapshot = value.String
			}
		case upstreamkeyratesnapshot.FieldKeyHashSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_hash_snapshot", values[i])
			} else if value.Valid {
				_m.KeyHashSnapshot = value.String
			}
		case upstreamkeyratesnapshot.FieldSyncRunID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sync_run_id", values[i])
			} else if value.Valid {
				_m.SyncRunID = new(int64)
				*_m.SyncRunID = value.Int64
			}
		case upstreamkeyratesnapshot.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case upstreamkeyratesnapshot.FieldRawRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field raw_rate_multiplier", values[i])
			} else if value.Valid {
				_m.RawRateMultiplier = value.Float64
			}
		case upstreamkeyratesnapshot.FieldRechargeRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field recharge_rate", values[i])
			} else if value.Valid {
				_m.RechargeRate = value.Float64
			}
		case upstreamkeyratesnapshot.FieldEffectiveCostMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field effective_cost_multiplier", values[i])
			} else if value.Valid {
				_m.EffectiveCostMultiplier = value.Float64
			}
		case upstreamkeyratesnapshot.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case upstreamkeyratesnapshot.FieldObservedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field observed_at", values[i])
			} else if value.Valid {
				_m.ObservedAt = value.Time
			}
		case upstreamkeyratesnapshot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamKeyRateSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamKeyRateSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConfig queries the "config" edge of the UpstreamKeyRateSnapshot entity.
func (_m *UpstreamKeyRateSnapshot) QueryConfig() *UpstreamConfigQuery {
	return NewUpstreamKeyRateSnapshotClient(_m.config).QueryConfig(_m)
}

// QueryKey queries the "key" edge of the UpstreamKeyRateSnapshot entity.
func (_m *UpstreamKeyRateSnapshot) QueryKey() *UpstreamKeyQuery {
	return NewUpstreamKeyRateSnapshotClient(_m.config).QueryKey(_m)
}

// QueryRun queries the "run" edge of the UpstreamKeyRateSnapshot entity.
func (_m *UpstreamKeyRateSnapshot) QueryRun() *UpstreamSyncRunQuery {
	return NewUpstreamKeyRateSnapshotClient(_m.config).QueryRun(_m)
}

// Update returns a builder for updating this UpstreamKeyRateSnapshot.
// Note that you need to call UpstreamKeyRateSnapshot.Unwrap() before calling this method if this UpstreamKeyRateSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamKeyRateSnapshot) Update() *UpstreamKeyRateSnapshotUpdateOne {
	return NewUpstreamKeyRateSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamKeyRateSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamKeyRateSnapshot) Unwrap() *UpstreamKeyRateSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamKeyRateSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamKeyRateSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamKeyRateSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("upstream_config_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamConfigID))
	builder.WriteString(", ")
	if v := _m.UpstreamKeyID; v != nil {
		builder.WriteString("upstream_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RemoteKeyID; v != nil {
		builder.WriteString("remote_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("key_name_snapshot=")
	builder.WriteString(_m.KeyNameSnapshot)
	builder.WriteString(", ")
	builder.WriteString("key_hash_snapshot=")
	builder.WriteString(_m.KeyHashSnapshot)
	builder.WriteString(", ")
	if v := _m.SyncRunID; v != nil {
		builder.WriteString("sync_run_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("raw_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RawRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("recharge_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.RechargeRate))
	builder.WriteString(", ")
	builder.WriteString("effective_cost_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.EffectiveCostMultiplier))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("observed_at=")
	builder.WriteString(_m.ObservedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamKeyRateSnapshots is a parsable slice of UpstreamKeyRateSnapshot.
type UpstreamKeyRateSnapshots []*UpstreamKeyRateSnapshot
