// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconfig"
	"github.com/Wei-Shaw/sub2api/ent/upstreamevent"
	"github.com/Wei-Shaw/sub2api/ent/upstreamincident"
	"github.com/Wei-Shaw/sub2api/ent/upstreamkey"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
)

// UpstreamKeyQuery is the builder for querying UpstreamKey entities.
type UpstreamKeyQuery struct {
	config
	ctx           *QueryContext
	order         []upstreamkey.OrderOption
	inters        []Interceptor
	predicates    []predicate.UpstreamKey
	withConfig    *UpstreamConfigQuery
	withAccounts  *AccountQuery
	withEvents    *UpstreamEventQuery
	withIncidents *UpstreamIncidentQuery
	withUsageLogs *UsageLogQuery
	modifiers     []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpstreamKeyQuery builder.
func (_q *UpstreamKeyQuery) Where(ps ...predicate.UpstreamKey) *UpstreamKeyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UpstreamKeyQuery) Limit(limit int) *UpstreamKeyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UpstreamKeyQuery) Offset(offset int) *UpstreamKeyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UpstreamKeyQuery) Unique(unique bool) *UpstreamKeyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UpstreamKeyQuery) Order(o ...upstreamkey.OrderOption) *UpstreamKeyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryConfig chains the current query on the "config" edge.
func (_q *UpstreamKeyQuery) QueryConfig() *UpstreamConfigQuery {
	query := (&UpstreamConfigClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(upstreamkey.Table, upstreamkey.FieldID, selector),
			sqlgraph.To(upstreamconfig.Table, upstreamconfig.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, upstreamkey.ConfigTable, upstreamkey.ConfigColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAccounts chains the current query on the "accounts" edge.
func (_q *UpstreamKeyQuery) QueryAccounts() *AccountQuery {
	query := (&AccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(upstreamkey.Table, upstreamkey.FieldID, selector),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, upstreamkey.AccountsTable, upstreamkey.AccountsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvents chains the current query on the "events" edge.
func (_q *UpstreamKeyQuery) QueryEvents() *UpstreamEventQuery {
	query := (&UpstreamEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(upstreamkey.Table, upstreamkey.FieldID, selector),
			sqlgraph.To(upstreamevent.Table, upstreamevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, upstreamkey.EventsTable, upstreamkey.EventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryIncidents chains the current query on the "incidents" edge.
func (_q *UpstreamKeyQuery) QueryIncidents() *UpstreamIncidentQuery {
	query := (&UpstreamIncidentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(upstreamkey.Table, upstreamkey.FieldID, selector),
			sqlgraph.To(upstreamincident.Table, upstreamincident.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, upstreamkey.IncidentsTable, upstreamkey.IncidentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsageLogs chains the current query on the "usage_logs" edge.
func (_q *UpstreamKeyQuery) QueryUsageLogs() *UsageLogQuery {
	query := (&UsageLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(upstreamkey.Table, upstreamkey.FieldID, selector),
			sqlgraph.To(usagelog.Table, usagelog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, upstreamkey.UsageLogsTable, upstreamkey.UsageLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UpstreamKey entity from the query.
// Returns a *NotFoundError when no UpstreamKey was found.
func (_q *UpstreamKeyQuery) First(ctx context.Context) (*UpstreamKey, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upstreamkey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UpstreamKeyQuery) FirstX(ctx context.Context) *UpstreamKey {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpstreamKey ID from the query.
// Returns a *NotFoundError when no UpstreamKey ID was found.
func (_q *UpstreamKeyQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upstreamkey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UpstreamKeyQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpstreamKey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpstreamKey entity is found.
// Returns a *NotFoundError when no UpstreamKey entities are found.
func (_q *UpstreamKeyQuery) Only(ctx context.Context) (*UpstreamKey, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upstreamkey.Label}
	default:
		return nil, &NotSingularError{upstreamkey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UpstreamKeyQuery) OnlyX(ctx context.Context) *UpstreamKey {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpstreamKey ID in the query.
// Returns a *NotSingularError when more than one UpstreamKey ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UpstreamKeyQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upstreamkey.Label}
	default:
		err = &NotSingularError{upstreamkey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UpstreamKeyQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpstreamKeys.
func (_q *UpstreamKeyQuery) All(ctx context.Context) ([]*UpstreamKey, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpstreamKey, *UpstreamKeyQuery]()
	return withInterceptors[[]*UpstreamKey](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UpstreamKeyQuery) AllX(ctx context.Context) []*UpstreamKey {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpstreamKey IDs.
func (_q *UpstreamKeyQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(upstreamkey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UpstreamKeyQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UpstreamKeyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UpstreamKeyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UpstreamKeyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UpstreamKeyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UpstreamKeyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpstreamKeyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UpstreamKeyQuery) Clone() *UpstreamKeyQuery {
	if _q == nil {
		return nil
	}
	return &UpstreamKeyQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]upstreamkey.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.UpstreamKey{}, _q.predicates...),
		withConfig:    _q.withConfig.Clone(),
		withAccounts:  _q.withAccounts.Clone(),
		withEvents:    _q.withEvents.Clone(),
		withIncidents: _q.withIncidents.Clone(),
		withUsageLogs: _q.withUsageLogs.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithConfig tells the query-builder to eager-load the nodes that are connected to
// the "config" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UpstreamKeyQuery) WithConfig(opts ...func(*UpstreamConfigQuery)) *UpstreamKeyQuery {
	query := (&UpstreamConfigClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withConfig = query
	return _q
}

// WithAccounts tells the query-builder to eager-load the nodes that are connected to
// the "accounts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UpstreamKeyQuery) WithAccounts(opts ...func(*AccountQuery)) *UpstreamKeyQuery {
	query := (&AccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAccounts = query
	return _q
}

// WithEvents tells the query-builder to eager-load the nodes that are connected to
// the "events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UpstreamKeyQuery) WithEvents(opts ...func(*UpstreamEventQuery)) *UpstreamKeyQuery {
	query := (&UpstreamEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvents = query
	return _q
}

// WithIncidents tells the query-builder to eager-load the nodes that are connected to
// the "incidents" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UpstreamKeyQuery) WithIncidents(opts ...func(*UpstreamIncidentQuery)) *UpstreamKeyQuery {
	query := (&UpstreamIncidentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withIncidents = query
	return _q
}

// WithUsageLogs tells the query-builder to eager-load the nodes that are connected to
// the "usage_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UpstreamKeyQuery) WithUsageLogs(opts ...func(*UsageLogQuery)) *UpstreamKeyQuery {
	query := (&UsageLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsageLogs = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpstreamKey.Query().
//		GroupBy(upstreamkey.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UpstreamKeyQuery) GroupBy(field string, fields ...string) *UpstreamKeyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpstreamKeyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = upstreamkey.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.UpstreamKey.Query().
//		Select(upstreamkey.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *UpstreamKeyQuery) Select(fields ...string) *UpstreamKeySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UpstreamKeySelect{UpstreamKeyQuery: _q}
	sbuild.label = upstreamkey.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpstreamKeySelect configured with the given aggregations.
func (_q *UpstreamKeyQuery) Aggregate(fns ...AggregateFunc) *UpstreamKeySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UpstreamKeyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !upstreamkey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *UpstreamKeyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpstreamKey, error) {
	var (
		nodes       = []*UpstreamKey{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withConfig != nil,
			_q.withAccounts != nil,
			_q.withEvents != nil,
			_q.withIncidents != nil,
			_q.withUsageLogs != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpstreamKey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpstreamKey{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withConfig; query != nil {
		if err := _q.loadConfig(ctx, query, nodes, nil,
			func(n *UpstreamKey, e *UpstreamConfig) { n.Edges.Config = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAccounts; query != nil {
		if err := _q.loadAccounts(ctx, query, nodes,
			func(n *UpstreamKey) { n.Edges.Accounts = []*Account{} },
			func(n *UpstreamKey, e *Account) { n.Edges.Accounts = append(n.Edges.Accounts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEvents; query != nil {
		if err := _q.loadEvents(ctx, query, nodes,
			func(n *UpstreamKey) { n.Edges.Events = []*UpstreamEvent{} },
			func(n *UpstreamKey, e *UpstreamEvent) { n.Edges.Events = append(n.Edges.Events, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withIncidents; query != nil {
		if err := _q.loadIncidents(ctx, query, nodes,
			func(n *UpstreamKey) { n.Edges.Incidents = []*UpstreamIncident{} },
			func(n *UpstreamKey, e *UpstreamIncident) { n.Edges.Incidents = append(n.Edges.Incidents, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUsageLogs; query != nil {
		if err := _q.loadUsageLogs(ctx, query, nodes,
			func(n *UpstreamKey) { n.Edges.UsageLogs = []*UsageLog{} },
			func(n *UpstreamKey, e *UsageLog) { n.Edges.UsageLogs = append(n.Edges.UsageLogs, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UpstreamKeyQuery) loadConfig(ctx context.Context, query *UpstreamConfigQuery, nodes []*UpstreamKey, init func(*UpstreamKey), assign func(*UpstreamKey, *UpstreamConfig)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UpstreamKey)
	for i := range nodes {
		fk := nodes[i].UpstreamConfigID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(upstreamconfig.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "upstream_config_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *UpstreamKeyQuery) loadAccounts(ctx context.Context, query *AccountQuery, nodes []*UpstreamKey, init func(*UpstreamKey), assign func(*UpstreamKey, *Account)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*UpstreamKey)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(account.FieldUpstreamKeyID)
	}
	query.Where(predicate.Account(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(upstreamkey.AccountsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UpstreamKeyID
		if fk == nil {
			return fmt.Errorf(`foreign-key "upstream_key_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "upstream_key_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UpstreamKeyQuery) loadEvents(ctx context.Context, query *UpstreamEventQuery, nodes []*UpstreamKey, init func(*UpstreamKey), assign func(*UpstreamKey, *UpstreamEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*UpstreamKey)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(upstreamevent.FieldUpstreamKeyID)
	}
	query.Where(predicate.UpstreamEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(upstreamkey.EventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UpstreamKeyID
		if fk == nil {
			return fmt.Errorf(`foreign-key "upstream_key_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "upstream_key_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UpstreamKeyQuery) loadIncidents(ctx context.Context, query *UpstreamIncidentQuery, nodes []*UpstreamKey, init func(*UpstreamKey), assign func(*UpstreamKey, *UpstreamIncident)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*UpstreamKey)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(upstreamincident.FieldUpstreamKeyID)
	}
	query.Where(predicate.UpstreamIncident(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(upstreamkey.IncidentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UpstreamKeyID
		if fk == nil {
			return fmt.Errorf(`foreign-key "upstream_key_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "upstream_key_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *UpstreamKeyQuery) loadUsageLogs(ctx context.Context, query *UsageLogQuery, nodes []*UpstreamKey, init func(*UpstreamKey), assign func(*UpstreamKey, *UsageLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*UpstreamKey)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usagelog.FieldUpstreamKeyID)
	}
	query.Where(predicate.UsageLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(upstreamkey.UsageLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.UpstreamKeyID
		if fk == nil {
			return fmt.Errorf(`foreign-key "upstream_key_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "upstream_key_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *UpstreamKeyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UpstreamKeyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upstreamkey.Table, upstreamkey.Columns, sqlgraph.NewFieldSpec(upstreamkey.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamkey.FieldID)
		for i := range fields {
			if fields[i] != upstreamkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withConfig != nil {
			_spec.Node.AddColumnOnce(upstreamkey.FieldUpstreamConfigID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UpstreamKeyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(upstreamkey.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = upstreamkey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *UpstreamKeyQuery) ForUpdate(opts ...sql.LockOption) *UpstreamKeyQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *UpstreamKeyQuery) ForShare(opts ...sql.LockOption) *UpstreamKeyQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// UpstreamKeyGroupBy is the group-by builder for UpstreamKey entities.
type UpstreamKeyGroupBy struct {
	selector
	build *UpstreamKeyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UpstreamKeyGroupBy) Aggregate(fns ...AggregateFunc) *UpstreamKeyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UpstreamKeyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpstreamKeyQuery, *UpstreamKeyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UpstreamKeyGroupBy) sqlScan(ctx context.Context, root *UpstreamKeyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpstreamKeySelect is the builder for selecting fields of UpstreamKey entities.
type UpstreamKeySelect struct {
	*UpstreamKeyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UpstreamKeySelect) Aggregate(fns ...AggregateFunc) *UpstreamKeySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UpstreamKeySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpstreamKeyQuery, *UpstreamKeySelect](ctx, _s.UpstreamKeyQuery, _s, _s.inters, v)
}

func (_s *UpstreamKeySelect) sqlScan(ctx context.Context, root *UpstreamKeyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
