// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamkey"
	"github.com/Wei-Shaw/sub2api/ent/upstreamkeymodelroute"
)

// UpstreamKeyModelRoute is the model entity for the UpstreamKeyModelRoute schema.
type UpstreamKeyModelRoute struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UpstreamKeyID holds the value of the "upstream_key_id" field.
	UpstreamKeyID int64 `json:"upstream_key_id,omitempty"`
	// PublicModel holds the value of the "public_model" field.
	PublicModel string `json:"public_model,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// TargetPlatform holds the value of the "target_platform" field.
	TargetPlatform string `json:"target_platform,omitempty"`
	// APIProtocol holds the value of the "api_protocol" field.
	APIProtocol string `json:"api_protocol,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LastSeenAt holds the value of the "last_seen_at" field.
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamKeyModelRouteQuery when eager-loading is set.
	Edges        UpstreamKeyModelRouteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamKeyModelRouteEdges holds the relations/edges for other nodes in the graph.
type UpstreamKeyModelRouteEdges struct {
	// Key holds the value of the key edge.
	Key *UpstreamKey `json:"key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// KeyOrErr returns the Key value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamKeyModelRouteEdges) KeyOrErr() (*UpstreamKey, error) {
	if e.Key != nil {
		return e.Key, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: upstreamkey.Label}
	}
	return nil, &NotLoadedError{edge: "key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamKeyModelRoute) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamkeymodelroute.FieldEnabled:
			values[i] = new(sql.NullBool)
		case upstreamkeymodelroute.FieldID, upstreamkeymodelroute.FieldUpstreamKeyID, upstreamkeymodelroute.FieldPriority:
			values[i] = new(sql.NullInt64)
		case upstreamkeymodelroute.FieldPublicModel, upstreamkeymodelroute.FieldUpstreamModel, upstreamkeymodelroute.FieldTargetPlatform, upstreamkeymodelroute.FieldAPIProtocol, upstreamkeymodelroute.FieldSource, upstreamkeymodelroute.FieldStatus, upstreamkeymodelroute.FieldLastError:
			values[i] = new(sql.NullString)
		case upstreamkeymodelroute.FieldCreatedAt, upstreamkeymodelroute.FieldUpdatedAt, upstreamkeymodelroute.FieldDeletedAt, upstreamkeymodelroute.FieldLastSeenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamKeyModelRoute fields.
func (_m *UpstreamKeyModelRoute) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamkeymodelroute.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamkeymodelroute.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamkeymodelroute.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstreamkeymodelroute.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case upstreamkeymodelroute.FieldUpstreamKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_key_id", values[i])
			} else if value.Valid {
				_m.UpstreamKeyID = value.Int64
			}
		case upstreamkeymodelroute.FieldPublicModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_model", values[i])
			} else if value.Valid {
				_m.PublicModel = value.String
			}
		case upstreamkeymodelroute.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case upstreamkeymodelroute.FieldTargetPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_platform", values[i])
			} else if value.Valid {
				_m.TargetPlatform = value.String
			}
		case upstreamkeymodelroute.FieldAPIProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_protocol", values[i])
			} else if value.Valid {
				_m.APIProtocol = value.String
			}
		case upstreamkeymodelroute.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case upstreamkeymodelroute.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case upstreamkeymodelroute.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case upstreamkeymodelroute.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case upstreamkeymodelroute.FieldLastSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_seen_at", values[i])
			} else if value.Valid {
				_m.LastSeenAt = new(time.Time)
				*_m.LastSeenAt = value.Time
			}
		case upstreamkeymodelroute.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamKeyModelRoute.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamKeyModelRoute) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryKey queries the "key" edge of the UpstreamKeyModelRoute entity.
func (_m *UpstreamKeyModelRoute) QueryKey() *UpstreamKeyQuery {
	return NewUpstreamKeyModelRouteClient(_m.config).QueryKey(_m)
}

// Update returns a builder for updating this UpstreamKeyModelRoute.
// Note that you need to call UpstreamKeyModelRoute.Unwrap() before calling this method if this UpstreamKeyModelRoute
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamKeyModelRoute) Update() *UpstreamKeyModelRouteUpdateOne {
	return NewUpstreamKeyModelRouteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamKeyModelRoute entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamKeyModelRoute) Unwrap() *UpstreamKeyModelRoute {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamKeyModelRoute is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamKeyModelRoute) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamKeyModelRoute(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("upstream_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamKeyID))
	builder.WriteString(", ")
	builder.WriteString("public_model=")
	builder.WriteString(_m.PublicModel)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("target_platform=")
	builder.WriteString(_m.TargetPlatform)
	builder.WriteString(", ")
	builder.WriteString("api_protocol=")
	builder.WriteString(_m.APIProtocol)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LastSeenAt; v != nil {
		builder.WriteString("last_seen_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamKeyModelRoutes is a parsable slice of UpstreamKeyModelRoute.
type UpstreamKeyModelRoutes []*UpstreamKeyModelRoute
