// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconfig"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsyncresult"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsyncrun"
)

// UpstreamSyncResultCreate is the builder for creating a UpstreamSyncResult entity.
type UpstreamSyncResultCreate struct {
	config
	mutation *UpstreamSyncResultMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSyncRunID sets the "sync_run_id" field.
func (_c *UpstreamSyncResultCreate) SetSyncRunID(v int64) *UpstreamSyncResultCreate {
	_c.mutation.SetSyncRunID(v)
	return _c
}

// SetUpstreamConfigID sets the "upstream_config_id" field.
func (_c *UpstreamSyncResultCreate) SetUpstreamConfigID(v int64) *UpstreamSyncResultCreate {
	_c.mutation.SetUpstreamConfigID(v)
	return _c
}

// SetConfigName sets the "config_name" field.
func (_c *UpstreamSyncResultCreate) SetConfigName(v string) *UpstreamSyncResultCreate {
	_c.mutation.SetConfigName(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *UpstreamSyncResultCreate) SetProvider(v string) *UpstreamSyncResultCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UpstreamSyncResultCreate) SetStatus(v string) *UpstreamSyncResultCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetStage sets the "stage" field.
func (_c *UpstreamSyncResultCreate) SetStage(v string) *UpstreamSyncResultCreate {
	_c.mutation.SetStage(v)
	return _c
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillableStage(v *string) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetStage(*v)
	}
	return _c
}

// SetErrorCode sets the "error_code" field.
func (_c *UpstreamSyncResultCreate) SetErrorCode(v string) *UpstreamSyncResultCreate {
	_c.mutation.SetErrorCode(v)
	return _c
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillableErrorCode(v *string) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetErrorCode(*v)
	}
	return _c
}

// SetSafeMessage sets the "safe_message" field.
func (_c *UpstreamSyncResultCreate) SetSafeMessage(v string) *UpstreamSyncResultCreate {
	_c.mutation.SetSafeMessage(v)
	return _c
}

// SetNillableSafeMessage sets the "safe_message" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillableSafeMessage(v *string) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetSafeMessage(*v)
	}
	return _c
}

// SetRetryable sets the "retryable" field.
func (_c *UpstreamSyncResultCreate) SetRetryable(v bool) *UpstreamSyncResultCreate {
	_c.mutation.SetRetryable(v)
	return _c
}

// SetNillableRetryable sets the "retryable" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillableRetryable(v *bool) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetRetryable(*v)
	}
	return _c
}

// SetHTTPStatus sets the "http_status" field.
func (_c *UpstreamSyncResultCreate) SetHTTPStatus(v int) *UpstreamSyncResultCreate {
	_c.mutation.SetHTTPStatus(v)
	return _c
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillableHTTPStatus(v *int) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetHTTPStatus(*v)
	}
	return _c
}

// SetRemoteKeyCount sets the "remote_key_count" field.
func (_c *UpstreamSyncResultCreate) SetRemoteKeyCount(v int) *UpstreamSyncResultCreate {
	_c.mutation.SetRemoteKeyCount(v)
	return _c
}

// SetNillableRemoteKeyCount sets the "remote_key_count" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillableRemoteKeyCount(v *int) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetRemoteKeyCount(*v)
	}
	return _c
}

// SetPersistedKeyCount sets the "persisted_key_count" field.
func (_c *UpstreamSyncResultCreate) SetPersistedKeyCount(v int) *UpstreamSyncResultCreate {
	_c.mutation.SetPersistedKeyCount(v)
	return _c
}

// SetNillablePersistedKeyCount sets the "persisted_key_count" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillablePersistedKeyCount(v *int) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetPersistedKeyCount(*v)
	}
	return _c
}

// SetFallbackKeyCount sets the "fallback_key_count" field.
func (_c *UpstreamSyncResultCreate) SetFallbackKeyCount(v int) *UpstreamSyncResultCreate {
	_c.mutation.SetFallbackKeyCount(v)
	return _c
}

// SetNillableFallbackKeyCount sets the "fallback_key_count" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillableFallbackKeyCount(v *int) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetFallbackKeyCount(*v)
	}
	return _c
}

// SetUnresolvedKeyCount sets the "unresolved_key_count" field.
func (_c *UpstreamSyncResultCreate) SetUnresolvedKeyCount(v int) *UpstreamSyncResultCreate {
	_c.mutation.SetUnresolvedKeyCount(v)
	return _c
}

// SetNillableUnresolvedKeyCount sets the "unresolved_key_count" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillableUnresolvedKeyCount(v *int) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetUnresolvedKeyCount(*v)
	}
	return _c
}

// SetUpdatedAccountCount sets the "updated_account_count" field.
func (_c *UpstreamSyncResultCreate) SetUpdatedAccountCount(v int) *UpstreamSyncResultCreate {
	_c.mutation.SetUpdatedAccountCount(v)
	return _c
}

// SetNillableUpdatedAccountCount sets the "updated_account_count" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillableUpdatedAccountCount(v *int) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetUpdatedAccountCount(*v)
	}
	return _c
}

// SetWarnings sets the "warnings" field.
func (_c *UpstreamSyncResultCreate) SetWarnings(v []string) *UpstreamSyncResultCreate {
	_c.mutation.SetWarnings(v)
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *UpstreamSyncResultCreate) SetDurationMs(v int64) *UpstreamSyncResultCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillableDurationMs(v *int64) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *UpstreamSyncResultCreate) SetStartedAt(v time.Time) *UpstreamSyncResultCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *UpstreamSyncResultCreate) SetFinishedAt(v time.Time) *UpstreamSyncResultCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamSyncResultCreate) SetCreatedAt(v time.Time) *UpstreamSyncResultCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamSyncResultCreate) SetNillableCreatedAt(v *time.Time) *UpstreamSyncResultCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRunID sets the "run" edge to the UpstreamSyncRun entity by ID.
func (_c *UpstreamSyncResultCreate) SetRunID(id int64) *UpstreamSyncResultCreate {
	_c.mutation.SetRunID(id)
	return _c
}

// SetRun sets the "run" edge to the UpstreamSyncRun entity.
func (_c *UpstreamSyncResultCreate) SetRun(v *UpstreamSyncRun) *UpstreamSyncResultCreate {
	return _c.SetRunID(v.ID)
}

// SetConfigID sets the "config" edge to the UpstreamConfig entity by ID.
func (_c *UpstreamSyncResultCreate) SetConfigID(id int64) *UpstreamSyncResultCreate {
	_c.mutation.SetConfigID(id)
	return _c
}

// SetConfig sets the "config" edge to the UpstreamConfig entity.
func (_c *UpstreamSyncResultCreate) SetConfig(v *UpstreamConfig) *UpstreamSyncResultCreate {
	return _c.SetConfigID(v.ID)
}

// Mutation returns the UpstreamSyncResultMutation object of the builder.
func (_c *UpstreamSyncResultCreate) Mutation() *UpstreamSyncResultMutation {
	return _c.mutation
}

// Save creates the UpstreamSyncResult in the database.
func (_c *UpstreamSyncResultCreate) Save(ctx context.Context) (*UpstreamSyncResult, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamSyncResultCreate) SaveX(ctx context.Context) *UpstreamSyncResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamSyncResultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamSyncResultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamSyncResultCreate) defaults() {
	if _, ok := _c.mutation.Stage(); !ok {
		v := upstreamsyncresult.DefaultStage
		_c.mutation.SetStage(v)
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		v := upstreamsyncresult.DefaultErrorCode
		_c.mutation.SetErrorCode(v)
	}
	if _, ok := _c.mutation.Retryable(); !ok {
		v := upstreamsyncresult.DefaultRetryable
		_c.mutation.SetRetryable(v)
	}
	if _, ok := _c.mutation.RemoteKeyCount(); !ok {
		v := upstreamsyncresult.DefaultRemoteKeyCount
		_c.mutation.SetRemoteKeyCount(v)
	}
	if _, ok := _c.mutation.PersistedKeyCount(); !ok {
		v := upstreamsyncresult.DefaultPersistedKeyCount
		_c.mutation.SetPersistedKeyCount(v)
	}
	if _, ok := _c.mutation.FallbackKeyCount(); !ok {
		v := upstreamsyncresult.DefaultFallbackKeyCount
		_c.mutation.SetFallbackKeyCount(v)
	}
	if _, ok := _c.mutation.UnresolvedKeyCount(); !ok {
		v := upstreamsyncresult.DefaultUnresolvedKeyCount
		_c.mutation.SetUnresolvedKeyCount(v)
	}
	if _, ok := _c.mutation.UpdatedAccountCount(); !ok {
		v := upstreamsyncresult.DefaultUpdatedAccountCount
		_c.mutation.SetUpdatedAccountCount(v)
	}
	if _, ok := _c.mutation.Warnings(); !ok {
		v := upstreamsyncresult.DefaultWarnings()
		_c.mutation.SetWarnings(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := upstreamsyncresult.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := upstreamsyncresult.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamSyncResultCreate) check() error {
	if _, ok := _c.mutation.SyncRunID(); !ok {
		return &ValidationError{Name: "sync_run_id", err: errors.New(`ent: missing required field "UpstreamSyncResult.sync_run_id"`)}
	}
	if _, ok := _c.mutation.UpstreamConfigID(); !ok {
		return &ValidationError{Name: "upstream_config_id", err: errors.New(`ent: missing required field "UpstreamSyncResult.upstream_config_id"`)}
	}
	if _, ok := _c.mutation.ConfigName(); !ok {
		return &ValidationError{Name: "config_name", err: errors.New(`ent: missing required field "UpstreamSyncResult.config_name"`)}
	}
	if v, ok := _c.mutation.ConfigName(); ok {
		if err := upstreamsyncresult.ConfigNameValidator(v); err != nil {
			return &ValidationError{Name: "config_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncResult.config_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "UpstreamSyncResult.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := upstreamsyncresult.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncResult.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UpstreamSyncResult.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := upstreamsyncresult.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncResult.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Stage(); !ok {
		return &ValidationError{Name: "stage", err: errors.New(`ent: missing required field "UpstreamSyncResult.stage"`)}
	}
	if v, ok := _c.mutation.Stage(); ok {
		if err := upstreamsyncresult.StageValidator(v); err != nil {
			return &ValidationError{Name: "stage", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncResult.stage": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ErrorCode(); !ok {
		return &ValidationError{Name: "error_code", err: errors.New(`ent: missing required field "UpstreamSyncResult.error_code"`)}
	}
	if v, ok := _c.mutation.ErrorCode(); ok {
		if err := upstreamsyncresult.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncResult.error_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Retryable(); !ok {
		return &ValidationError{Name: "retryable", err: errors.New(`ent: missing required field "UpstreamSyncResult.retryable"`)}
	}
	if _, ok := _c.mutation.RemoteKeyCount(); !ok {
		return &ValidationError{Name: "remote_key_count", err: errors.New(`ent: missing required field "UpstreamSyncResult.remote_key_count"`)}
	}
	if _, ok := _c.mutation.PersistedKeyCount(); !ok {
		return &ValidationError{Name: "persisted_key_count", err: errors.New(`ent: missing required field "UpstreamSyncResult.persisted_key_count"`)}
	}
	if _, ok := _c.mutation.FallbackKeyCount(); !ok {
		return &ValidationError{Name: "fallback_key_count", err: errors.New(`ent: missing required field "UpstreamSyncResult.fallback_key_count"`)}
	}
	if _, ok := _c.mutation.UnresolvedKeyCount(); !ok {
		return &ValidationError{Name: "unresolved_key_count", err: errors.New(`ent: missing required field "UpstreamSyncResult.unresolved_key_count"`)}
	}
	if _, ok := _c.mutation.UpdatedAccountCount(); !ok {
		return &ValidationError{Name: "updated_account_count", err: errors.New(`ent: missing required field "UpstreamSyncResult.updated_account_count"`)}
	}
	if _, ok := _c.mutation.Warnings(); !ok {
		return &ValidationError{Name: "warnings", err: errors.New(`ent: missing required field "UpstreamSyncResult.warnings"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "UpstreamSyncResult.duration_ms"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "UpstreamSyncResult.started_at"`)}
	}
	if _, ok := _c.mutation.FinishedAt(); !ok {
		return &ValidationError{Name: "finished_at", err: errors.New(`ent: missing required field "UpstreamSyncResult.finished_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamSyncResult.created_at"`)}
	}
	if len(_c.mutation.RunIDs()) == 0 {
		return &ValidationError{Name: "run", err: errors.New(`ent: missing required edge "UpstreamSyncResult.run"`)}
	}
	if len(_c.mutation.ConfigIDs()) == 0 {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required edge "UpstreamSyncResult.config"`)}
	}
	return nil
}

func (_c *UpstreamSyncResultCreate) sqlSave(ctx context.Context) (*UpstreamSyncResult, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamSyncResultCreate) createSpec() (*UpstreamSyncResult, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamSyncResult{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamsyncresult.Table, sqlgraph.NewFieldSpec(upstreamsyncresult.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ConfigName(); ok {
		_spec.SetField(upstreamsyncresult.FieldConfigName, field.TypeString, value)
		_node.ConfigName = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(upstreamsyncresult.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(upstreamsyncresult.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Stage(); ok {
		_spec.SetField(upstreamsyncresult.FieldStage, field.TypeString, value)
		_node.Stage = value
	}
	if value, ok := _c.mutation.ErrorCode(); ok {
		_spec.SetField(upstreamsyncresult.FieldErrorCode, field.TypeString, value)
		_node.ErrorCode = value
	}
	if value, ok := _c.mutation.SafeMessage(); ok {
		_spec.SetField(upstreamsyncresult.FieldSafeMessage, field.TypeString, value)
		_node.SafeMessage = &value
	}
	if value, ok := _c.mutation.Retryable(); ok {
		_spec.SetField(upstreamsyncresult.FieldRetryable, field.TypeBool, value)
		_node.Retryable = value
	}
	if value, ok := _c.mutation.HTTPStatus(); ok {
		_spec.SetField(upstreamsyncresult.FieldHTTPStatus, field.TypeInt, value)
		_node.HTTPStatus = &value
	}
	if value, ok := _c.mutation.RemoteKeyCount(); ok {
		_spec.SetField(upstreamsyncresult.FieldRemoteKeyCount, field.TypeInt, value)
		_node.RemoteKeyCount = value
	}
	if value, ok := _c.mutation.PersistedKeyCount(); ok {
		_spec.SetField(upstreamsyncresult.FieldPersistedKeyCount, field.TypeInt, value)
		_node.PersistedKeyCount = value
	}
	if value, ok := _c.mutation.FallbackKeyCount(); ok {
		_spec.SetField(upstreamsyncresult.FieldFallbackKeyCount, field.TypeInt, value)
		_node.FallbackKeyCount = value
	}
	if value, ok := _c.mutation.UnresolvedKeyCount(); ok {
		_spec.SetField(upstreamsyncresult.FieldUnresolvedKeyCount, field.TypeInt, value)
		_node.UnresolvedKeyCount = value
	}
	if value, ok := _c.mutation.UpdatedAccountCount(); ok {
		_spec.SetField(upstreamsyncresult.FieldUpdatedAccountCount, field.TypeInt, value)
		_node.UpdatedAccountCount = value
	}
	if value, ok := _c.mutation.Warnings(); ok {
		_spec.SetField(upstreamsyncresult.FieldWarnings, field.TypeJSON, value)
		_node.Warnings = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(upstreamsyncresult.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(upstreamsyncresult.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(upstreamsyncresult.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamsyncresult.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamsyncresult.RunTable,
			Columns: []string{upstreamsyncresult.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsyncrun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SyncRunID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamsyncresult.ConfigTable,
			Columns: []string{upstreamsyncresult.ConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UpstreamConfigID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamSyncResult.Create().
//		SetSyncRunID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamSyncResultUpsert) {
//			SetSyncRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamSyncResultCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamSyncResultUpsertOne {
	_c.conflict = opts
	return &UpstreamSyncResultUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamSyncResult.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamSyncResultCreate) OnConflictColumns(columns ...string) *UpstreamSyncResultUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamSyncResultUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamSyncResultUpsertOne is the builder for "upsert"-ing
	//  one UpstreamSyncResult node.
	UpstreamSyncResultUpsertOne struct {
		create *UpstreamSyncResultCreate
	}

	// UpstreamSyncResultUpsert is the "OnConflict" setter.
	UpstreamSyncResultUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamSyncResult.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamSyncResultUpsertOne) UpdateNewValues() *UpstreamSyncResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.SyncRunID(); exists {
			s.SetIgnore(upstreamsyncresult.FieldSyncRunID)
		}
		if _, exists := u.create.mutation.UpstreamConfigID(); exists {
			s.SetIgnore(upstreamsyncresult.FieldUpstreamConfigID)
		}
		if _, exists := u.create.mutation.ConfigName(); exists {
			s.SetIgnore(upstreamsyncresult.FieldConfigName)
		}
		if _, exists := u.create.mutation.Provider(); exists {
			s.SetIgnore(upstreamsyncresult.FieldProvider)
		}
		if _, exists := u.create.mutation.Status(); exists {
			s.SetIgnore(upstreamsyncresult.FieldStatus)
		}
		if _, exists := u.create.mutation.Stage(); exists {
			s.SetIgnore(upstreamsyncresult.FieldStage)
		}
		if _, exists := u.create.mutation.ErrorCode(); exists {
			s.SetIgnore(upstreamsyncresult.FieldErrorCode)
		}
		if _, exists := u.create.mutation.SafeMessage(); exists {
			s.SetIgnore(upstreamsyncresult.FieldSafeMessage)
		}
		if _, exists := u.create.mutation.Retryable(); exists {
			s.SetIgnore(upstreamsyncresult.FieldRetryable)
		}
		if _, exists := u.create.mutation.HTTPStatus(); exists {
			s.SetIgnore(upstreamsyncresult.FieldHTTPStatus)
		}
		if _, exists := u.create.mutation.RemoteKeyCount(); exists {
			s.SetIgnore(upstreamsyncresult.FieldRemoteKeyCount)
		}
		if _, exists := u.create.mutation.PersistedKeyCount(); exists {
			s.SetIgnore(upstreamsyncresult.FieldPersistedKeyCount)
		}
		if _, exists := u.create.mutation.FallbackKeyCount(); exists {
			s.SetIgnore(upstreamsyncresult.FieldFallbackKeyCount)
		}
		if _, exists := u.create.mutation.UnresolvedKeyCount(); exists {
			s.SetIgnore(upstreamsyncresult.FieldUnresolvedKeyCount)
		}
		if _, exists := u.create.mutation.UpdatedAccountCount(); exists {
			s.SetIgnore(upstreamsyncresult.FieldUpdatedAccountCount)
		}
		if _, exists := u.create.mutation.Warnings(); exists {
			s.SetIgnore(upstreamsyncresult.FieldWarnings)
		}
		if _, exists := u.create.mutation.DurationMs(); exists {
			s.SetIgnore(upstreamsyncresult.FieldDurationMs)
		}
		if _, exists := u.create.mutation.StartedAt(); exists {
			s.SetIgnore(upstreamsyncresult.FieldStartedAt)
		}
		if _, exists := u.create.mutation.FinishedAt(); exists {
			s.SetIgnore(upstreamsyncresult.FieldFinishedAt)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamsyncresult.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamSyncResult.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamSyncResultUpsertOne) Ignore() *UpstreamSyncResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamSyncResultUpsertOne) DoNothing() *UpstreamSyncResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamSyncResultCreate.OnConflict
// documentation for more info.
func (u *UpstreamSyncResultUpsertOne) Update(set func(*UpstreamSyncResultUpsert)) *UpstreamSyncResultUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamSyncResultUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *UpstreamSyncResultUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamSyncResultCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamSyncResultUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamSyncResultUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamSyncResultUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamSyncResultCreateBulk is the builder for creating many UpstreamSyncResult entities in bulk.
type UpstreamSyncResultCreateBulk struct {
	config
	err      error
	builders []*UpstreamSyncResultCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamSyncResult entities in the database.
func (_c *UpstreamSyncResultCreateBulk) Save(ctx context.Context) ([]*UpstreamSyncResult, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamSyncResult, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamSyncResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamSyncResultCreateBulk) SaveX(ctx context.Context) []*UpstreamSyncResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamSyncResultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamSyncResultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamSyncResult.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamSyncResultUpsert) {
//			SetSyncRunID(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamSyncResultCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamSyncResultUpsertBulk {
	_c.conflict = opts
	return &UpstreamSyncResultUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamSyncResult.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamSyncResultCreateBulk) OnConflictColumns(columns ...string) *UpstreamSyncResultUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamSyncResultUpsertBulk{
		create: _c,
	}
}

// UpstreamSyncResultUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamSyncResult nodes.
type UpstreamSyncResultUpsertBulk struct {
	create *UpstreamSyncResultCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamSyncResult.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamSyncResultUpsertBulk) UpdateNewValues() *UpstreamSyncResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.SyncRunID(); exists {
				s.SetIgnore(upstreamsyncresult.FieldSyncRunID)
			}
			if _, exists := b.mutation.UpstreamConfigID(); exists {
				s.SetIgnore(upstreamsyncresult.FieldUpstreamConfigID)
			}
			if _, exists := b.mutation.ConfigName(); exists {
				s.SetIgnore(upstreamsyncresult.FieldConfigName)
			}
			if _, exists := b.mutation.Provider(); exists {
				s.SetIgnore(upstreamsyncresult.FieldProvider)
			}
			if _, exists := b.mutation.Status(); exists {
				s.SetIgnore(upstreamsyncresult.FieldStatus)
			}
			if _, exists := b.mutation.Stage(); exists {
				s.SetIgnore(upstreamsyncresult.FieldStage)
			}
			if _, exists := b.mutation.ErrorCode(); exists {
				s.SetIgnore(upstreamsyncresult.FieldErrorCode)
			}
			if _, exists := b.mutation.SafeMessage(); exists {
				s.SetIgnore(upstreamsyncresult.FieldSafeMessage)
			}
			if _, exists := b.mutation.Retryable(); exists {
				s.SetIgnore(upstreamsyncresult.FieldRetryable)
			}
			if _, exists := b.mutation.HTTPStatus(); exists {
				s.SetIgnore(upstreamsyncresult.FieldHTTPStatus)
			}
			if _, exists := b.mutation.RemoteKeyCount(); exists {
				s.SetIgnore(upstreamsyncresult.FieldRemoteKeyCount)
			}
			if _, exists := b.mutation.PersistedKeyCount(); exists {
				s.SetIgnore(upstreamsyncresult.FieldPersistedKeyCount)
			}
			if _, exists := b.mutation.FallbackKeyCount(); exists {
				s.SetIgnore(upstreamsyncresult.FieldFallbackKeyCount)
			}
			if _, exists := b.mutation.UnresolvedKeyCount(); exists {
				s.SetIgnore(upstreamsyncresult.FieldUnresolvedKeyCount)
			}
			if _, exists := b.mutation.UpdatedAccountCount(); exists {
				s.SetIgnore(upstreamsyncresult.FieldUpdatedAccountCount)
			}
			if _, exists := b.mutation.Warnings(); exists {
				s.SetIgnore(upstreamsyncresult.FieldWarnings)
			}
			if _, exists := b.mutation.DurationMs(); exists {
				s.SetIgnore(upstreamsyncresult.FieldDurationMs)
			}
			if _, exists := b.mutation.StartedAt(); exists {
				s.SetIgnore(upstreamsyncresult.FieldStartedAt)
			}
			if _, exists := b.mutation.FinishedAt(); exists {
				s.SetIgnore(upstreamsyncresult.FieldFinishedAt)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamsyncresult.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamSyncResult.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamSyncResultUpsertBulk) Ignore() *UpstreamSyncResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamSyncResultUpsertBulk) DoNothing() *UpstreamSyncResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamSyncResultCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamSyncResultUpsertBulk) Update(set func(*UpstreamSyncResultUpsert)) *UpstreamSyncResultUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamSyncResultUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *UpstreamSyncResultUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamSyncResultCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamSyncResultCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamSyncResultUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
