export default {
    upstreamDashboard: {
      title: 'Upstream Dashboard', description: 'Review traffic, health, performance, and estimated returns by upstream configuration.', empty: 'No upstream configurations match the filters.', openDetail: 'Open details for {name}', noReason: 'No reason recorded', estimatedUnavailable: 'Estimate unavailable',
      windows: { '1h': '1 hour', '24h': '24 hours', '7d': '7 days', '15d': '15 days', '30d': '30 days' },
      filters: { title: 'Filter scope', window: 'Time window', provider: 'Provider', status: 'Status', sort: 'Status order', sortAsc: 'Switch to ascending order', sortDesc: 'Switch to descending order', searchLabel: 'Search channels', allProviders: 'All providers', allStatuses: 'All statuses' },
      summary: { configurations: 'Configurations', withTraffic: 'With live traffic', needAttention: 'Need attention', schedulableAccounts: 'Schedulable accounts', openIncidents: 'Open incidents', balanceLow: 'Low-balance channels' },
      windowLabel: 'Window: {window}', lastUpdated: 'Updated {time}', lastProbe: 'Last {time}', emptyHint: 'Adjust the filters or wait for new traffic and probe data.', noTrafficData: 'No live traffic in this window.', noTrendData: 'No trend data in this window.',
      status: { operational: 'Operational', degraded: 'Degraded', critical: 'Critical', disabled: 'Disabled', data_insufficient: 'Insufficient data', healthy: 'Healthy', success: 'Success', error: 'Error', failed: 'Failed', suspended: 'Suspended', stale: 'Stale', unknown: 'Unknown' },
      reasons: { probe_succeeded: 'Probe completed', traffic_succeeded: 'Real request succeeded', authentication_failed: 'Upstream authentication failed', capacity_limited: 'Upstream capacity or rate limited', upstream_server_error: 'Upstream server error', probe_transport_error: 'Probe connection or transport failed', probe_response_mismatch: 'Probe response mismatch', probe_incomplete_stream: 'Probe stream ended early', probe_http_error: 'Probe HTTP error', probe_request_failed: 'Probe request failed', probe_quality_degraded: 'Probe quality degraded', gateway_intercepted: 'Gateway or WAF interception', currency_unavailable: 'Currency conversion unavailable', no_snapshot: 'No balance snapshot', stale_snapshot: 'Balance snapshot is stale', threshold_not_configured: 'Low-balance threshold is not configured' },
      confidence: { current_success: 'Current success', mixed: 'Mixed result', unsuccessful: 'Unsuccessful', data_insufficient: 'Insufficient data' },
      events: { balance_low: 'Low balance', recharge_rate_changed: 'Recharge rate changed', key_rate_changed: 'Key rate changed', key_effective_rate_changed: 'Key effective rate changed', key_actual_rate_changed: 'Key actual rate changed', currency_conversion_changed: 'Currency conversion changed' },
      metrics: { requests: 'Requests', successRate: 'Success rate', ttft: 'P50 TTFT', latency: 'P50 latency', p95ttft: 'P95 TTFT', p95latency: 'P95 latency', failed: 'Failed', timeouts: 'Timeouts', authErrors: 'Auth/config', accounts: 'Schedulable accounts', tempUnschedulable: 'Temporarily unschedulable', probeSamples: 'Probe samples', confidence: 'Confidence', estimatedProfit: 'Estimated gross profit', balance: 'Balance', balanceLow: 'Low balance, recharge required', balanceThreshold: 'Alert threshold {amount}', openIncidents: 'Open incidents', lastRateChange: 'Last rate change', lastRateChangeAt: 'Last rate change: {time}', rateChanged: 'Rate changed', rateChangedAt: 'Rate changed {time}', balanceUpdated: 'Balance updated {time}', balanceUnavailable: 'Balance unavailable' },
      sections: { trend: 'Traffic trend', traffic: 'Live traffic', probe: 'Active probes', operations: 'Operations signals', accounts: 'Account composition', profit: 'Cost & returns', errors: 'Recent errors' },
      noIncidentData: 'No open incidents', noRateChangeData: 'No rate changes',
      actions: { channels: 'View channels', accounts: 'View accounts', usage: 'View usage' }
    },
    upstreamChannels: { title: 'Upstream Channels', description: 'Manage upstream configurations, key synchronization, and channel operations.' },
    upstreamAccounts: { title: 'Upstream Accounts', description: 'Manage upstream accounts, health, and capabilities.' }
}
