// Code generated by ent, DO NOT EDIT.

package upstreamsyncrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the upstreamsyncrun type in the database.
	Label = "upstream_sync_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTrigger holds the string denoting the trigger field in the database.
	FieldTrigger = "trigger"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldTotalConfigs holds the string denoting the total_configs field in the database.
	FieldTotalConfigs = "total_configs"
	// FieldSuccessConfigs holds the string denoting the success_configs field in the database.
	FieldSuccessConfigs = "success_configs"
	// FieldPartialConfigs holds the string denoting the partial_configs field in the database.
	FieldPartialConfigs = "partial_configs"
	// FieldFailedConfigs holds the string denoting the failed_configs field in the database.
	FieldFailedConfigs = "failed_configs"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeResults holds the string denoting the results edge name in mutations.
	EdgeResults = "results"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// EdgeBalanceSnapshots holds the string denoting the balance_snapshots edge name in mutations.
	EdgeBalanceSnapshots = "balance_snapshots"
	// Table holds the table name of the upstreamsyncrun in the database.
	Table = "upstream_sync_runs"
	// ResultsTable is the table that holds the results relation/edge.
	ResultsTable = "upstream_sync_results"
	// ResultsInverseTable is the table name for the UpstreamSyncResult entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamsyncresult" package.
	ResultsInverseTable = "upstream_sync_results"
	// ResultsColumn is the table column denoting the results relation/edge.
	ResultsColumn = "sync_run_id"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "upstream_events"
	// EventsInverseTable is the table name for the UpstreamEvent entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamevent" package.
	EventsInverseTable = "upstream_events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "sync_run_id"
	// BalanceSnapshotsTable is the table that holds the balance_snapshots relation/edge.
	BalanceSnapshotsTable = "upstream_balance_snapshots"
	// BalanceSnapshotsInverseTable is the table name for the UpstreamBalanceSnapshot entity.
	// It exists in this package in order to avoid circular dependency with the "upstreambalancesnapshot" package.
	BalanceSnapshotsInverseTable = "upstream_balance_snapshots"
	// BalanceSnapshotsColumn is the table column denoting the balance_snapshots relation/edge.
	BalanceSnapshotsColumn = "sync_run_id"
)

// Columns holds all SQL columns for upstreamsyncrun fields.
var Columns = []string{
	FieldID,
	FieldTrigger,
	FieldStatus,
	FieldStartedAt,
	FieldFinishedAt,
	FieldTotalConfigs,
	FieldSuccessConfigs,
	FieldPartialConfigs,
	FieldFailedConfigs,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TriggerValidator is a validator for the "trigger" field. It is called by the builders before save.
	TriggerValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultTotalConfigs holds the default value on creation for the "total_configs" field.
	DefaultTotalConfigs int
	// DefaultSuccessConfigs holds the default value on creation for the "success_configs" field.
	DefaultSuccessConfigs int
	// DefaultPartialConfigs holds the default value on creation for the "partial_configs" field.
	DefaultPartialConfigs int
	// DefaultFailedConfigs holds the default value on creation for the "failed_configs" field.
	DefaultFailedConfigs int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UpstreamSyncRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTrigger orders the results by the trigger field.
func ByTrigger(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrigger, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByTotalConfigs orders the results by the total_configs field.
func ByTotalConfigs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalConfigs, opts...).ToFunc()
}

// BySuccessConfigs orders the results by the success_configs field.
func BySuccessConfigs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessConfigs, opts...).ToFunc()
}

// ByPartialConfigs orders the results by the partial_configs field.
func ByPartialConfigs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPartialConfigs, opts...).ToFunc()
}

// ByFailedConfigs orders the results by the failed_configs field.
func ByFailedConfigs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailedConfigs, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByResultsCount orders the results by results count.
func ByResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newResultsStep(), opts...)
	}
}

// ByResults orders the results by results terms.
func ByResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBalanceSnapshotsCount orders the results by balance_snapshots count.
func ByBalanceSnapshotsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBalanceSnapshotsStep(), opts...)
	}
}

// ByBalanceSnapshots orders the results by balance_snapshots terms.
func ByBalanceSnapshots(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBalanceSnapshotsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ResultsTable, ResultsColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
func newBalanceSnapshotsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BalanceSnapshotsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BalanceSnapshotsTable, BalanceSnapshotsColumn),
	)
}
