// Code generated by ent, DO NOT EDIT.

package upstreamconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldName, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldProvider, v))
}

// SiteURL applies equality check predicate on the "site_url" field. It's identical to SiteURLEQ.
func SiteURL(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldSiteURL, v))
}

// APIURL applies equality check predicate on the "api_url" field. It's identical to APIURLEQ.
func APIURL(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldAPIURL, v))
}

// AuthMode applies equality check predicate on the "auth_mode" field. It's identical to AuthModeEQ.
func AuthMode(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldAuthMode, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldProxyID, v))
}

// RechargeRate applies equality check predicate on the "recharge_rate" field. It's identical to RechargeRateEQ.
func RechargeRate(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldRechargeRate, v))
}

// BalanceToCnyRate applies equality check predicate on the "balance_to_cny_rate" field. It's identical to BalanceToCnyRateEQ.
func BalanceToCnyRate(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldBalanceToCnyRate, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldStatus, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldLastError, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastSuccessAt applies equality check predicate on the "last_success_at" field. It's identical to LastSuccessAtEQ.
func LastSuccessAt(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldLastSuccessAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContainsFold(FieldName, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContainsFold(FieldProvider, v))
}

// SiteURLEQ applies the EQ predicate on the "site_url" field.
func SiteURLEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldSiteURL, v))
}

// SiteURLNEQ applies the NEQ predicate on the "site_url" field.
func SiteURLNEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldSiteURL, v))
}

// SiteURLIn applies the In predicate on the "site_url" field.
func SiteURLIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldSiteURL, vs...))
}

// SiteURLNotIn applies the NotIn predicate on the "site_url" field.
func SiteURLNotIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldSiteURL, vs...))
}

// SiteURLGT applies the GT predicate on the "site_url" field.
func SiteURLGT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldSiteURL, v))
}

// SiteURLGTE applies the GTE predicate on the "site_url" field.
func SiteURLGTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldSiteURL, v))
}

// SiteURLLT applies the LT predicate on the "site_url" field.
func SiteURLLT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldSiteURL, v))
}

// SiteURLLTE applies the LTE predicate on the "site_url" field.
func SiteURLLTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldSiteURL, v))
}

// SiteURLContains applies the Contains predicate on the "site_url" field.
func SiteURLContains(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContains(FieldSiteURL, v))
}

// SiteURLHasPrefix applies the HasPrefix predicate on the "site_url" field.
func SiteURLHasPrefix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasPrefix(FieldSiteURL, v))
}

// SiteURLHasSuffix applies the HasSuffix predicate on the "site_url" field.
func SiteURLHasSuffix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasSuffix(FieldSiteURL, v))
}

// SiteURLEqualFold applies the EqualFold predicate on the "site_url" field.
func SiteURLEqualFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEqualFold(FieldSiteURL, v))
}

// SiteURLContainsFold applies the ContainsFold predicate on the "site_url" field.
func SiteURLContainsFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContainsFold(FieldSiteURL, v))
}

// APIURLEQ applies the EQ predicate on the "api_url" field.
func APIURLEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldAPIURL, v))
}

// APIURLNEQ applies the NEQ predicate on the "api_url" field.
func APIURLNEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldAPIURL, v))
}

// APIURLIn applies the In predicate on the "api_url" field.
func APIURLIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldAPIURL, vs...))
}

// APIURLNotIn applies the NotIn predicate on the "api_url" field.
func APIURLNotIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldAPIURL, vs...))
}

// APIURLGT applies the GT predicate on the "api_url" field.
func APIURLGT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldAPIURL, v))
}

// APIURLGTE applies the GTE predicate on the "api_url" field.
func APIURLGTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldAPIURL, v))
}

// APIURLLT applies the LT predicate on the "api_url" field.
func APIURLLT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldAPIURL, v))
}

// APIURLLTE applies the LTE predicate on the "api_url" field.
func APIURLLTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldAPIURL, v))
}

// APIURLContains applies the Contains predicate on the "api_url" field.
func APIURLContains(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContains(FieldAPIURL, v))
}

// APIURLHasPrefix applies the HasPrefix predicate on the "api_url" field.
func APIURLHasPrefix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasPrefix(FieldAPIURL, v))
}

// APIURLHasSuffix applies the HasSuffix predicate on the "api_url" field.
func APIURLHasSuffix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasSuffix(FieldAPIURL, v))
}

// APIURLIsNil applies the IsNil predicate on the "api_url" field.
func APIURLIsNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIsNull(FieldAPIURL))
}

// APIURLNotNil applies the NotNil predicate on the "api_url" field.
func APIURLNotNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotNull(FieldAPIURL))
}

// APIURLEqualFold applies the EqualFold predicate on the "api_url" field.
func APIURLEqualFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEqualFold(FieldAPIURL, v))
}

// APIURLContainsFold applies the ContainsFold predicate on the "api_url" field.
func APIURLContainsFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContainsFold(FieldAPIURL, v))
}

// AuthModeEQ applies the EQ predicate on the "auth_mode" field.
func AuthModeEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldAuthMode, v))
}

// AuthModeNEQ applies the NEQ predicate on the "auth_mode" field.
func AuthModeNEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldAuthMode, v))
}

// AuthModeIn applies the In predicate on the "auth_mode" field.
func AuthModeIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldAuthMode, vs...))
}

// AuthModeNotIn applies the NotIn predicate on the "auth_mode" field.
func AuthModeNotIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldAuthMode, vs...))
}

// AuthModeGT applies the GT predicate on the "auth_mode" field.
func AuthModeGT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldAuthMode, v))
}

// AuthModeGTE applies the GTE predicate on the "auth_mode" field.
func AuthModeGTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldAuthMode, v))
}

// AuthModeLT applies the LT predicate on the "auth_mode" field.
func AuthModeLT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldAuthMode, v))
}

// AuthModeLTE applies the LTE predicate on the "auth_mode" field.
func AuthModeLTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldAuthMode, v))
}

// AuthModeContains applies the Contains predicate on the "auth_mode" field.
func AuthModeContains(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContains(FieldAuthMode, v))
}

// AuthModeHasPrefix applies the HasPrefix predicate on the "auth_mode" field.
func AuthModeHasPrefix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasPrefix(FieldAuthMode, v))
}

// AuthModeHasSuffix applies the HasSuffix predicate on the "auth_mode" field.
func AuthModeHasSuffix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasSuffix(FieldAuthMode, v))
}

// AuthModeEqualFold applies the EqualFold predicate on the "auth_mode" field.
func AuthModeEqualFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEqualFold(FieldAuthMode, v))
}

// AuthModeContainsFold applies the ContainsFold predicate on the "auth_mode" field.
func AuthModeContainsFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContainsFold(FieldAuthMode, v))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDIsNil applies the IsNil predicate on the "proxy_id" field.
func ProxyIDIsNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIsNull(FieldProxyID))
}

// ProxyIDNotNil applies the NotNil predicate on the "proxy_id" field.
func ProxyIDNotNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotNull(FieldProxyID))
}

// RechargeRateEQ applies the EQ predicate on the "recharge_rate" field.
func RechargeRateEQ(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldRechargeRate, v))
}

// RechargeRateNEQ applies the NEQ predicate on the "recharge_rate" field.
func RechargeRateNEQ(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldRechargeRate, v))
}

// RechargeRateIn applies the In predicate on the "recharge_rate" field.
func RechargeRateIn(vs ...float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldRechargeRate, vs...))
}

// RechargeRateNotIn applies the NotIn predicate on the "recharge_rate" field.
func RechargeRateNotIn(vs ...float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldRechargeRate, vs...))
}

// RechargeRateGT applies the GT predicate on the "recharge_rate" field.
func RechargeRateGT(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldRechargeRate, v))
}

// RechargeRateGTE applies the GTE predicate on the "recharge_rate" field.
func RechargeRateGTE(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldRechargeRate, v))
}

// RechargeRateLT applies the LT predicate on the "recharge_rate" field.
func RechargeRateLT(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldRechargeRate, v))
}

// RechargeRateLTE applies the LTE predicate on the "recharge_rate" field.
func RechargeRateLTE(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldRechargeRate, v))
}

// BalanceToCnyRateEQ applies the EQ predicate on the "balance_to_cny_rate" field.
func BalanceToCnyRateEQ(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldBalanceToCnyRate, v))
}

// BalanceToCnyRateNEQ applies the NEQ predicate on the "balance_to_cny_rate" field.
func BalanceToCnyRateNEQ(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldBalanceToCnyRate, v))
}

// BalanceToCnyRateIn applies the In predicate on the "balance_to_cny_rate" field.
func BalanceToCnyRateIn(vs ...float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldBalanceToCnyRate, vs...))
}

// BalanceToCnyRateNotIn applies the NotIn predicate on the "balance_to_cny_rate" field.
func BalanceToCnyRateNotIn(vs ...float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldBalanceToCnyRate, vs...))
}

// BalanceToCnyRateGT applies the GT predicate on the "balance_to_cny_rate" field.
func BalanceToCnyRateGT(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldBalanceToCnyRate, v))
}

// BalanceToCnyRateGTE applies the GTE predicate on the "balance_to_cny_rate" field.
func BalanceToCnyRateGTE(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldBalanceToCnyRate, v))
}

// BalanceToCnyRateLT applies the LT predicate on the "balance_to_cny_rate" field.
func BalanceToCnyRateLT(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldBalanceToCnyRate, v))
}

// BalanceToCnyRateLTE applies the LTE predicate on the "balance_to_cny_rate" field.
func BalanceToCnyRateLTE(v float64) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldBalanceToCnyRate, v))
}

// BalanceToCnyRateIsNil applies the IsNil predicate on the "balance_to_cny_rate" field.
func BalanceToCnyRateIsNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIsNull(FieldBalanceToCnyRate))
}

// BalanceToCnyRateNotNil applies the NotNil predicate on the "balance_to_cny_rate" field.
func BalanceToCnyRateNotNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotNull(FieldBalanceToCnyRate))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContainsFold(FieldStatus, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldContainsFold(FieldLastError, v))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotNull(FieldLastCheckedAt))
}

// LastSuccessAtEQ applies the EQ predicate on the "last_success_at" field.
func LastSuccessAtEQ(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtNEQ applies the NEQ predicate on the "last_success_at" field.
func LastSuccessAtNEQ(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNEQ(FieldLastSuccessAt, v))
}

// LastSuccessAtIn applies the In predicate on the "last_success_at" field.
func LastSuccessAtIn(vs ...time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtNotIn applies the NotIn predicate on the "last_success_at" field.
func LastSuccessAtNotIn(vs ...time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotIn(FieldLastSuccessAt, vs...))
}

// LastSuccessAtGT applies the GT predicate on the "last_success_at" field.
func LastSuccessAtGT(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGT(FieldLastSuccessAt, v))
}

// LastSuccessAtGTE applies the GTE predicate on the "last_success_at" field.
func LastSuccessAtGTE(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldGTE(FieldLastSuccessAt, v))
}

// LastSuccessAtLT applies the LT predicate on the "last_success_at" field.
func LastSuccessAtLT(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLT(FieldLastSuccessAt, v))
}

// LastSuccessAtLTE applies the LTE predicate on the "last_success_at" field.
func LastSuccessAtLTE(v time.Time) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldLTE(FieldLastSuccessAt, v))
}

// LastSuccessAtIsNil applies the IsNil predicate on the "last_success_at" field.
func LastSuccessAtIsNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldIsNull(FieldLastSuccessAt))
}

// LastSuccessAtNotNil applies the NotNil predicate on the "last_success_at" field.
func LastSuccessAtNotNil() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.FieldNotNull(FieldLastSuccessAt))
}

// HasKeys applies the HasEdge predicate on the "keys" edge.
func HasKeys() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, KeysTable, KeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeysWith applies the HasEdge predicate on the "keys" edge with a given conditions (other predicates).
func HasKeysWith(preds ...predicate.UpstreamKey) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := newKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSyncResults applies the HasEdge predicate on the "sync_results" edge.
func HasSyncResults() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SyncResultsTable, SyncResultsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSyncResultsWith applies the HasEdge predicate on the "sync_results" edge with a given conditions (other predicates).
func HasSyncResultsWith(preds ...predicate.UpstreamSyncResult) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := newSyncResultsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.UpstreamEvent) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIncidents applies the HasEdge predicate on the "incidents" edge.
func HasIncidents() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IncidentsTable, IncidentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIncidentsWith applies the HasEdge predicate on the "incidents" edge with a given conditions (other predicates).
func HasIncidentsWith(preds ...predicate.UpstreamIncident) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := newIncidentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBalanceSnapshots applies the HasEdge predicate on the "balance_snapshots" edge.
func HasBalanceSnapshots() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, BalanceSnapshotsTable, BalanceSnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBalanceSnapshotsWith applies the HasEdge predicate on the "balance_snapshots" edge with a given conditions (other predicates).
func HasBalanceSnapshotsWith(preds ...predicate.UpstreamBalanceSnapshot) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := newBalanceSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasKeyRateSnapshots applies the HasEdge predicate on the "key_rate_snapshots" edge.
func HasKeyRateSnapshots() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, KeyRateSnapshotsTable, KeyRateSnapshotsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasKeyRateSnapshotsWith applies the HasEdge predicate on the "key_rate_snapshots" edge with a given conditions (other predicates).
func HasKeyRateSnapshotsWith(preds ...predicate.UpstreamKeyRateSnapshot) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := newKeyRateSnapshotsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProxy applies the HasEdge predicate on the "proxy" edge.
func HasProxy() predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProxyTable, ProxyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProxyWith applies the HasEdge predicate on the "proxy" edge with a given conditions (other predicates).
func HasProxyWith(preds ...predicate.Proxy) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(func(s *sql.Selector) {
		step := newProxyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamConfig) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamConfig) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamConfig) predicate.UpstreamConfig {
	return predicate.UpstreamConfig(sql.NotPredicates(p))
}
