// Code generated by ent, DO NOT EDIT.

package proxyipgroupmember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ProxyIPGroupID applies equality check predicate on the "proxy_ip_group_id" field. It's identical to ProxyIPGroupIDEQ.
func ProxyIPGroupID(v int64) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldEQ(FieldProxyIPGroupID, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldEQ(FieldProxyID, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldEQ(FieldPosition, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldEQ(FieldCreatedAt, v))
}

// ProxyIPGroupIDEQ applies the EQ predicate on the "proxy_ip_group_id" field.
func ProxyIPGroupIDEQ(v int64) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldEQ(FieldProxyIPGroupID, v))
}

// ProxyIPGroupIDNEQ applies the NEQ predicate on the "proxy_ip_group_id" field.
func ProxyIPGroupIDNEQ(v int64) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldNEQ(FieldProxyIPGroupID, v))
}

// ProxyIPGroupIDIn applies the In predicate on the "proxy_ip_group_id" field.
func ProxyIPGroupIDIn(vs ...int64) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldIn(FieldProxyIPGroupID, vs...))
}

// ProxyIPGroupIDNotIn applies the NotIn predicate on the "proxy_ip_group_id" field.
func ProxyIPGroupIDNotIn(vs ...int64) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldNotIn(FieldProxyIPGroupID, vs...))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldNotIn(FieldProxyID, vs...))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldLTE(FieldPosition, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.FieldLTE(FieldCreatedAt, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, GroupColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.ProxyIPGroup) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProxy applies the HasEdge predicate on the "proxy" edge.
func HasProxy() predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, ProxyColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, ProxyTable, ProxyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProxyWith applies the HasEdge predicate on the "proxy" edge with a given conditions (other predicates).
func HasProxyWith(preds ...predicate.Proxy) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(func(s *sql.Selector) {
		step := newProxyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProxyIPGroupMember) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProxyIPGroupMember) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProxyIPGroupMember) predicate.ProxyIPGroupMember {
	return predicate.ProxyIPGroupMember(sql.NotPredicates(p))
}
